package com.kwad.sdk.core.config;

import com.bytedance.sdk.openadsdk.downloadnew.core.TTDownloadField;
import com.kwad.sdk.core.config.item.InstallActivateReminderConfigItem;
import com.kwad.sdk.core.config.item.TipsConfigItem;
import com.kwad.sdk.core.config.item.e;
import com.kwad.sdk.core.config.item.f;
import com.kwad.sdk.core.config.item.g;
import com.kwad.sdk.core.config.item.h;
import com.kwad.sdk.core.config.item.i;
import com.kwad.sdk.core.config.item.j;
import com.kwad.sdk.core.config.item.k;
import com.kwad.sdk.core.config.item.l;
import com.kwad.sdk.core.config.item.m;
import com.kwad.sdk.core.config.item.n;
import com.kwad.sdk.core.config.item.o;
import com.kwad.sdk.core.config.item.p;
import com.kwad.sdk.core.config.item.q;
import java.util.ArrayList;
/* loaded from: classes.dex */
public final class c {
    public static k akr = new k("batchReportCatchLimit", 20);
    public static k aks = new k("exceptionCollectorSwitch", 1);
    public static k akt = new k("mediaPlayerLogReport", 0);
    public static k aku = new k("didCopySwitch", 1);
    public static k akv = new k("enableHodor", 0);
    public static k akw = new k("speedLimitSwitch", 1);
    public static k akx = new k("speedLimitThreshold", 200);
    public static k aky = new k("ksNativeAdCustomSwitch", 0);
    public static k akz = new k("forceActivateAfterInstalled", 0);
    public static k akA = new k("spliceVideoInteractionType", 0);
    public static k akB = new k("feedPreLoadOptimze", 0);
    public static k akC = new k("interstitialAdLoadProcessChange", 0);
    public static k akD = new k("formAdExitInterceptSwitch", 0);
    public static k akE = new k("adLeaveConfirmSwitch", 0);
    public static k akF = new k("viewLandingPageTaskDuration", 15);
    public static k akG = new k("rewardAdVideoPreCacheSize", 800);
    public static com.kwad.sdk.core.config.item.d akH = new com.kwad.sdk.core.config.item.d("dataFlowAutoStartSwitch", false);
    public static m akI = new m("deviceInfoDisableConfig", 0L);
    public static com.kwad.sdk.core.config.item.d akJ = new com.kwad.sdk.core.config.item.d("playerEnable", false);
    public static com.kwad.sdk.core.config.item.d akK = new com.kwad.sdk.core.config.item.d("dynamicEnable", false);
    public static k akL = new k("commercialLoggerSwitch", 1);
    public static p akM = new p("tkSoUrlV7a", "");
    public static p akN = new p("tkSoUrlV8a", "");
    public static com.kwad.sdk.core.config.item.d akO = new com.kwad.sdk.core.config.item.d("useTKSoAll", false);
    public static l akP = new l("playerConfig", null);
    public static q akQ = new q("pkgNameList", new ArrayList(0));
    public static q akR = new q("hostList", new ArrayList(0));
    public static q akS = new q("crashGatherRateConfigList", new ArrayList(0));
    public static TipsConfigItem akT = new TipsConfigItem();
    public static com.kwad.sdk.core.config.item.c akU = new com.kwad.sdk.core.config.item.c();
    public static InstallActivateReminderConfigItem akV = new InstallActivateReminderConfigItem();
    public static e akW = new e();
    public static n akX = new n("realtimeReportActions", "");
    public static o akY = new o();
    public static k akZ = new k("appInstallNoticeSecond", 0);
    public static k ala = new k("installFloatingLayerPostion", 0);
    public static k alb = new k("remindInstallStyle", 0);
    public static k alc = new k("remindInstallTime", 60);
    public static k ald = new k("watermarkKwaiIdSwitch", 0);
    public static k ale = new k("insertScreenV2Switch", 0);
    public static k alf = new k("insertScreenAutoPlaySwitch", 0);
    public static j alg = new j("insertScreenV2ShowConfig");
    public static k alh = new k("environmentDetectEnable", 0);
    public static k ali = new k("simCardInfoEnable", 0);
    public static k alj = new k("baseStationEnable", 0);
    public static k alk = new k("sensorEventEnable2", 0);
    public static k all = new k("lpAutoDownloadApkSwitch", 1);
    public static k alm = new k("autoDownloadUrlSwitch", 0);
    public static k aln = new k("insertScreenAdType", 0);
    public static k alo = new k("interstitialAutoCallAppCountDaily", 1);
    public static k alp = new k("mediaControlPlaySwitch", 1);
    public static p alq = new p("appStatusSoUrlV7a", "");
    public static p alr = new p("appStatusSoUrlV8a", "");
    public static p als = new p("appStatusSoVersion", "");
    public static k alt = new k("deeplinkCheckSwitch", -3);
    public static com.kwad.sdk.core.config.item.d alu = new com.kwad.sdk.core.config.item.d("deeplinkWindowSwitch", false);
    public static h alv = new h();
    public static com.kwad.sdk.core.config.item.d alw = new com.kwad.sdk.core.config.item.d("adLiveSwitch", false);
    public static com.kwad.sdk.core.config.item.d alx = new com.kwad.sdk.core.config.item.d("TKSwitch", true);
    public static com.kwad.sdk.core.config.item.d aly = new com.kwad.sdk.core.config.item.d("llsidDisplaySwitch", true);
    public static com.kwad.sdk.core.config.item.d alz = new com.kwad.sdk.core.config.item.d("reduceDeviceSigSwitch", true);
    public static com.kwad.sdk.core.config.item.d alA = new com.kwad.sdk.core.config.item.d("personalRecommend", false);
    public static k alB = new k("forceActivate", 0);
    public static k alC = new k("remindOpen", -1);
    public static com.kwad.sdk.core.config.item.d alD = new com.kwad.sdk.core.config.item.d("viewVisibleCheckLegacy", false);
    public static k alE = new k("enableAnrReportReal", 0);
    public static k alF = new k("enableNativeCrashReport", 0);
    public static p alG = new p("exceptionSoUrlV7a", "");
    public static p alH = new p("exceptionSoUrlV8a", "");
    public static k alI = new k("kwaiAppVersionSwitch", 1);
    public static p alJ = new p(TTDownloadField.TT_USERAGENT, com.kwad.sdk.core.network.q.getDefaultUserAgent());
    public static k alK = new k("biddingLogSwitch", 0);
    public static k alL = new k("forceActiveThreshold", 5);
    public static k alM = new k("forceActiveInterval", 3);
    public static k alN = new k("hybridEnable", 1);
    public static com.kwad.sdk.core.config.item.d alO = new com.kwad.sdk.core.config.item.d("wifiResumeDownload", false);
    public static g alP = new g("adExposureAreaPercent", 0.3f);
    public static g alQ = new g("adExposureTime", -1.0f);
    public static g alR = new g("apmToRECommercialRatio", 0.0f);
    public static com.kwad.sdk.core.config.item.d alS = new com.kwad.sdk.core.config.item.d("appInAdExposureBlacklist", false);
    public static com.kwad.sdk.core.config.item.d alT = new com.kwad.sdk.core.config.item.d("soDownloadBreakpointContinuation", true);
    public static k alU = new k("soLoadMaxRetryCount", 1);
    public static com.kwad.sdk.core.config.item.d alV = new com.kwad.sdk.core.config.item.d("feedAdForceGetAudioFocus", false);
    public static k alW = new k("feedAdWebviewOptimize", 1);
    public static com.kwad.sdk.core.config.item.d alX = new com.kwad.sdk.core.config.item.d("logCommandSwitch", false);
    public static com.kwad.sdk.core.config.item.d alY = new com.kwad.sdk.core.config.item.d("logRecordAllSwitch", false);
    public static m alZ = new m("obiwanLogFilesDiskQuota", 52428800L);
    public static l ama = new l("logCommandResult", "", false);
    public static m amb = new m("validClickConvertTime", 1000L);
    public static k amc = new k("playableAutoPlayEnable", 1);
    public static k amd = new k("netMonitorSwitch", 0);
    public static com.kwad.sdk.core.config.item.d ame = new com.kwad.sdk.core.config.item.d("ipDirectEnable", false);
    public static com.kwad.sdk.core.config.item.d amf = new com.kwad.sdk.core.config.item.d("ipPreferEnable", false);
    public static k amg = new k("weaponSwitch", 1);
    public static k amh = new k("kvModeV2", 0);
    public static i ami = new i();
    public static m amj = new m("currentServerTimeMs");
    public static k amk = new k("clientProofreadTimeErrorRangeHours", 100);
    public static g aml = new g("adTraceReportRate", 1.0f);
    public static k amm = new k("adTraceRepeatEnable", 0);
    public static k amn = new k("appHeartBeatInterval", 0);
    public static k amo = new k("adCacheCode", 0);
    public static p amp = new p("installTipsContentDesc", "");
    public static p amq = new p("installTipsPositiveActionDesc", "");
    public static p amr = new p("installTipsNegativeActionDesc", "");
    public static com.kwad.sdk.core.config.item.d ams = new com.kwad.sdk.core.config.item.d("threadOptEnable", false);
    public static p amt = new p("perfMonitorV2", "");
    public static k amu = new k("neoVideoAdaptStrategy", 1);
    public static com.kwad.sdk.core.config.item.d amv = new com.kwad.sdk.core.config.item.d("adCacheOptEnable", false);
    public static com.kwad.sdk.core.config.item.d amw = new com.kwad.sdk.core.config.item.d("autoShowActivityMiddlePage", false);
    public static p amx = new p("ranger", "");
    public static p amy = new p("threadPoolPerfMonitor", "");
    public static p amz = new p("threadPoolParams", "");
    public static f amA = new f("crashUploadRate", Double.valueOf(1.0d));
    public static com.kwad.sdk.core.config.item.d amB = new com.kwad.sdk.core.config.item.d("enableHookPluginResource", true);
    public static com.kwad.sdk.core.config.item.d amC = new com.kwad.sdk.core.config.item.d("enableHookWrapperContext", true);
    public static com.kwad.sdk.core.config.item.d amD = new com.kwad.sdk.core.config.item.d("batchReportSkipJSONParseEnable", true);
    public static com.kwad.sdk.core.config.item.d amE = new com.kwad.sdk.core.config.item.d("enableAdTrackLog", true);

    public static void init() {
    }
}
