package com.fyber.inneractive.sdk.h;

import androidx.room.RoomDatabase;
import com.facebook.internal.FacebookRequestErrorClassification;
import com.ironsource.mediationsdk.logger.IronSourceError;
import com.ironsource.mediationsdk.utils.IronSourceConstants;
import okhttp3.internal.http.StatusLine;
/* loaded from: classes.dex */
public enum l {
    VAST_ERROR_INVALID_RESPONSE(301),
    VAST_ERROR_TOO_MANY_WRAPPERS(IronSourceConstants.OFFERWALL_AVAILABLE),
    VAST_ERROR_NO_MEDIA_FILES(303),
    VAST_ERROR_NO_COMPATIBLE_MEDIA_FILE(304),
    VAST_ERROR_PRE_BUFFER_TIMEOUT(306),
    VAST_ERROR_BUFFER_TIMEOUT(StatusLine.HTTP_TEMP_REDIRECT),
    VAST_ERROR_FAILED_PLAYING_MEDIA_FILE(StatusLine.HTTP_PERM_REDIRECT),
    VAST_ERROR_FAILED_PLAYING_ALL_MEDIA_FILES(311),
    VAST_ERROR_UNSECURE_URL(312),
    MRAID_ERROR_UNSECURE_CONTENT(313),
    VPAID_ERROR_UNSECURE_CONTENT(314),
    VAST_UNKNOWN_PLAYER_ERROR(399),
    NATIVE_ERROR_INVALID_NATIVE_RESPONSE(401),
    NATIVE_ERROR_MISSING_PUB_REQUIRED_FIELD(402),
    NATIVE_ERROR_MISMATCH_REQUIRED_ASSET_RESPONSE(404),
    NATIVE_ERROR_INVALID_REQUIRED_ASSET_DATA(405),
    NATIVE_ERROR_INVALID_OPTIONAL_ASSET_DATA(406),
    NATIVE_ERROR_INVALID_LINK_WEB_URL(407),
    NATIVE_ERROR_FAILED_LOAD_ASSET(410),
    NATIVE_ERROR_MISMATCH_OPTIONAL_ASSET_RESPONSE(411),
    NATIVE_ERROR_MISSING_PROTOCOL_REQUIRED_FIELD(FacebookRequestErrorClassification.EC_APP_NOT_INSTALLED),
    NATIVE_ERROR_RECEIVED_VIDEO_BUT_NOT_SUPPORTED(413),
    NATIVE_ERROR_NO_VALID_URLS_FOR_CLICK(414),
    NATIVE_ERROR_SOME_INVALID_URLS_FOR_PROCESSED_CLICK(415),
    MRAID_AUTO_ACTION_DETECTED(IronSourceError.ERROR_CODE_NO_CONFIGURATION_AVAILABLE),
    INTERNAL_CONFIG_MISMATCH(IronSourceError.ERROR_BN_LOAD_AFTER_LONG_INITIATION),
    FATAL_CONFIGURATION_ERROR(701),
    FATAL_FEATURES_CONFIG_ERROR(704),
    MRAID_VIDEO_HAS_NOT_STARTED_PLAYING_IN_A_TIMELY_FASHION(390),
    VAST_COMPANION_FAILED_LOADING(70),
    CLICK_PARSING_FAILURE(991),
    IA_UNCAUGHT_EXCEPTION(RoomDatabase.MAX_BIND_PARAMETER_CNT),
    MISSMATCH_SPOTID(992),
    IA_AD_LOAD_FAILED(801),
    IA_AD_EXPIRED(802),
    IA_AD_DESTROYED_WITHOUT_SHOW(803),
    FETCH_TOKEN_DV_ERROR(1000),
    DV_ERROR_PHASE(1001),
    FMP_SDK_INIT_FAILED(62);
    
    int N;

    l(int i) {
        this.N = i;
    }

    /* JADX INFO: Access modifiers changed from: package-private */
    public static String a() {
        return am.ERROR_TABLE.c;
    }
}
