package com.kwad.sdk.core.b.a;

import com.kwad.components.core.webview.a.a;
import com.kwad.components.core.webview.b.a.h;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveMessageListener;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveShopListener;
import com.kwad.components.core.webview.jshandler.WebCardVideoPositionHandler;
import com.kwad.components.core.webview.jshandler.ab;
import com.kwad.components.core.webview.jshandler.ac;
import com.kwad.components.core.webview.jshandler.af;
import com.kwad.components.core.webview.jshandler.ag;
import com.kwad.components.core.webview.jshandler.ah;
import com.kwad.components.core.webview.jshandler.ak;
import com.kwad.components.core.webview.jshandler.al;
import com.kwad.components.core.webview.jshandler.am;
import com.kwad.components.core.webview.jshandler.an;
import com.kwad.components.core.webview.jshandler.aq;
import com.kwad.components.core.webview.jshandler.at;
import com.kwad.components.core.webview.jshandler.au;
import com.kwad.components.core.webview.jshandler.av;
import com.kwad.components.core.webview.jshandler.ax;
import com.kwad.components.core.webview.jshandler.b;
import com.kwad.components.core.webview.jshandler.c;
import com.kwad.components.core.webview.jshandler.d;
import com.kwad.components.core.webview.jshandler.e;
import com.kwad.components.core.webview.jshandler.f;
import com.kwad.components.core.webview.jshandler.h;
import com.kwad.components.core.webview.jshandler.i;
import com.kwad.components.core.webview.jshandler.m;
import com.kwad.components.core.webview.jshandler.n;
import com.kwad.components.core.webview.jshandler.q;
import com.kwad.components.core.webview.jshandler.y;
import com.kwad.components.core.webview.jshandler.z;
import com.kwad.sdk.i.a;
import com.kwad.sdk.i.b;
/* loaded from: classes.dex */
public final class bz {
    public static void AP() {
        ey.AQ().put(d.a.class, new dq());
        ey.AQ().put(e.a.class, new dr());
        ey.AQ().put(com.kwad.components.core.webview.b.b.p.class, new gm());
        ey.AQ().put(com.kwad.components.core.webview.b.b.w.class, new jf());
        ey.AQ().put(a.b.class, new cp());
        ey.AQ().put(an.a.class, new ay());
        ey.AQ().put(y.a.class, new gp());
        ey.AQ().put(com.kwad.components.core.webview.b.b.v.class, new jd());
        ey.AQ().put(com.kwad.components.core.webview.b.b.j.class, new ew());
        ey.AQ().put(com.kwad.components.core.webview.b.b.i.class, new dv());
        ey.AQ().put(com.kwad.components.core.webview.b.b.l.class, new fc());
        ey.AQ().put(com.kwad.components.core.webview.b.b.y.class, new jk());
        ey.AQ().put(com.kwad.components.core.webview.b.b.d.class, new ax());
        ey.AQ().put(m.a.class, new im());
        ey.AQ().put(af.a.class, new cc());
        ey.AQ().put(b.C0268b.class, new hl());
        ey.AQ().put(f.b.class, new dt());
        ey.AQ().put(q.a.class, new q());
        ey.AQ().put(h.b.class, new go());
        ey.AQ().put(ab.a.class, new je());
        ey.AQ().put(com.kwad.components.core.webview.a.b.class, new fz());
        ey.AQ().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.AdLiveMessageItemInfo.class, new x());
        ey.AQ().put(WebCardVideoPositionHandler.VideoPosition.class, new jj());
        ey.AQ().put(f.a.class, new ds());
        ey.AQ().put(a.C0267a.class, new cs());
        ey.AQ().put(com.kwad.components.core.n.b.class, new fy());
        ey.AQ().put(i.a.class, new ek());
        ey.AQ().put(com.kwad.components.core.webview.b.b.h.class, new cg());
        ey.AQ().put(com.kwad.components.core.webview.b.b.c.class, new av());
        ey.AQ().put(b.a.class, new hk());
        ey.AQ().put(com.kwad.components.core.webview.b.b.n.class, new ga());
        ey.AQ().put(am.b.class, new as());
        ey.AQ().put(n.b.class, new ii());
        ey.AQ().put(com.kwad.components.core.webview.a.c.class, new gb());
        ey.AQ().put(au.a.class, new is());
        ey.AQ().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.class, new w());
        ey.AQ().put(c.a.class, new dp());
        ey.AQ().put(aq.a.class, new fe());
        ey.AQ().put(al.a.class, new ap());
        ey.AQ().put(com.kwad.components.core.webview.b.b.x.class, new jh());
        ey.AQ().put(h.a.class, new du());
        ey.AQ().put(com.kwad.components.core.webview.b.b.f.class, new bn());
        ey.AQ().put(com.kwad.components.core.k.a.class, new p());
        ey.AQ().put(a.C0213a.class, new cm());
        ey.AQ().put(com.kwad.components.core.webview.b.b.s.class, new hr());
        ey.AQ().put(com.kwad.components.core.webview.b.b.g.class, new bq());
        ey.AQ().put(com.kwad.components.core.webview.b.b.q.class, new ho());
        ey.AQ().put(i.b.class, new el());
        ey.AQ().put(com.kwad.components.core.webview.b.b.b.class, new at());
        ey.AQ().put(com.kwad.components.core.webview.b.b.t.class, new hs());
        ey.AQ().put(com.kwad.components.core.webview.b.b.m.class, new fo());
        ey.AQ().put(com.kwad.components.core.webview.b.b.u.class, new ic());
        ey.AQ().put(av.a.class, new dz());
        ey.AQ().put(com.kwad.components.core.webview.b.b.e.class, new bg());
        ey.AQ().put(ax.a.class, new ex());
        ey.AQ().put(ac.a.class, new eb());
        ey.AQ().put(b.C0219b.class, new ee());
        ey.AQ().put(WebCardRegisterLiveShopListener.AdLiveItemShopInfo.class, new v());
        ey.AQ().put(com.kwad.components.core.webview.b.b.r.class, new hq());
        ey.AQ().put(com.kwad.components.core.webview.b.b.a.class, new m());
        ey.AQ().put(com.kwad.components.core.webview.b.b.o.class, new ge());
        ey.AQ().put(ah.b.class, new ev());
        ey.AQ().put(am.a.class, new ar());
        ey.AQ().put(z.a.class, new gq());
        ey.AQ().put(ak.a.class, new gg());
        ey.AQ().put(WebCardVideoPositionHandler.VideoPosition.KSAdJSCornerModel.class, new ez());
        ey.AQ().put(com.kwad.sdk.a.a.a.a.class, new em());
        ey.AQ().put(ah.a.class, new eu());
        ey.AQ().put(at.a.class, new jl());
        ey.AQ().put(ag.b.class, new dx());
    }
}
