package com.kwad.sdk.core.b.a;

import com.ksad.annotation.invoker.ForInvoker;
import com.kwad.sdk.commercial.model.HybridLoadMsg;
import com.kwad.sdk.commercial.model.SDKInitMsg;
import com.kwad.sdk.commercial.model.WebCloseStatus;
import com.kwad.sdk.commercial.model.WebViewCommercialMsg;
import com.kwad.sdk.commercial.model.WebViewLoadMsg;
import com.kwad.sdk.core.imageloader.ImageLoaderInfo;
import com.kwad.sdk.core.request.model.StatusInfo;
import com.kwad.sdk.core.response.model.ABParams;
import com.kwad.sdk.core.response.model.AdInfo;
import com.kwad.sdk.core.response.model.AdMatrixInfo;
import com.kwad.sdk.core.response.model.AdProductInfo;
import com.kwad.sdk.core.response.model.AdStatusInfo;
import com.kwad.sdk.core.response.model.AdStyleInfo;
import com.kwad.sdk.core.response.model.AdTemplate;
import com.kwad.sdk.core.response.model.CouponInfo;
import com.kwad.sdk.core.response.model.FeedSlideConf;
import com.kwad.sdk.core.response.model.HttpDnsInfo;
import com.kwad.sdk.core.response.model.PageInfo;
import com.kwad.sdk.core.response.model.PhotoInfo;
import com.kwad.sdk.core.response.model.TKAdLiveShopItemInfo;
import com.kwad.sdk.core.response.model.TemplateConfig;
import com.kwad.sdk.core.response.model.VideoPlayerStatus;
import com.kwad.sdk.core.scene.URLPackage;
import com.kwad.sdk.internal.api.AdLabelImpl;
import com.kwad.sdk.internal.api.NativeAdExtraDataImpl;
import com.kwad.sdk.internal.api.SceneImpl;
import com.kwad.sdk.internal.api.SplashExtraDataImpl;
import com.kwad.sdk.m.k;
import java.util.HashMap;
import java.util.Map;
/* loaded from: classes.dex */
public final class ey {
    public static Map<Class<? extends com.kwad.sdk.core.response.a.a>, com.kwad.sdk.core.d> aoz;

    static {
        HashMap hashMap = new HashMap();
        aoz = hashMap;
        hashMap.put(AdMatrixInfo.AggregationCardInfo.class, new an());
        aoz.put(AdMatrixInfo.SplashActionBarInfo.class, new hv());
        aoz.put(AdStatusInfo.class, new af());
        aoz.put(AdInfo.AdAggregateInfo.class, new h());
        aoz.put(PhotoInfo.class, new gk());
        aoz.put(AdInfo.AdFeedInfo.class, new o());
        aoz.put(AdStyleInfo.FeedAdInfo.class, new db());
        aoz.put(AdInfo.AdBaseInfo.class, new i());
        aoz.put(AdInfo.AdStyleConfInfo.class, new ag());
        aoz.put(PageInfo.class, new gf());
        aoz.put(com.kwad.sdk.utils.b.a.class, new fb());
        aoz.put(AdInfo.NativeAdInfo.class, new fq());
        aoz.put(AdInfo.AdConversionInfo.DeeplinkItemInfo.class, new ch());
        aoz.put(AdMatrixInfo.RewardWebTaskCloseInfo.class, new hf());
        aoz.put(AdMatrixInfo.AdInteractionInfo.class, new t());
        aoz.put(AdInfo.AdShowVideoH5Info.class, new ad());
        aoz.put(AdStyleInfo.PlayDetailInfo.ActionBarInfo.class, new c());
        aoz.put(AdInfo.AdMaterialInfo.MaterialFeature.class, new fi());
        aoz.put(com.kwad.sdk.core.request.model.b.class, new cl());
        aoz.put(StatusInfo.class, new il());
        aoz.put(AdStyleInfo.PlayEndInfo.class, new gn());
        aoz.put(AdMatrixInfo.FeedInfo.class, new dc());
        aoz.put(AdInfo.AdInsertScreenInfo.class, new s());
        aoz.put(AdMatrixInfo.NeoVideoInfo.class, new fv());
        aoz.put(AdMatrixInfo.RotateInfo.class, new hi());
        aoz.put(AdStyleInfo.PlayDetailInfo.PatchAdInfo.class, new gi());
        aoz.put(StatusInfo.NativeAdStyleControl.class, new ft());
        aoz.put(AdStyleInfo.PlayDetailInfo.WidgetAdInfo.class, new jp());
        aoz.put(AdInfo.FullScreenVideoInfo.class, new dn());
        aoz.put(AdMatrixInfo.StyleInfo.class, new in());
        aoz.put(AdMatrixInfo.MerchantLiveReservationInfo.LiveReservationPlayEndInfo.class, new fd());
        aoz.put(AdMatrixInfo.BottomBannerInfo.class, new bf());
        aoz.put(AdStyleInfo.ExtraDisplayInfo.class, new cz());
        aoz.put(TemplateConfig.class, new it());
        aoz.put(HybridLoadMsg.class, new ed());
        aoz.put(AdInfo.AdSplashInfo.class, new ae());
        aoz.put(TKAdLiveShopItemInfo.class, new ip());
        aoz.put(AdMatrixInfo.SplashSlideInfo.class, new ie());
        aoz.put(AdTemplate.class, new ai());
        aoz.put(AdInfo.NativeAdShakeInfo.class, new fs());
        aoz.put(AdInfo.MaterialSize.class, new fj());
        aoz.put(AdStyleInfo.PlayEndInfo.AdWebCardInfo.class, new al());
        aoz.put(ImageLoaderInfo.class, new eg());
        aoz.put(AdInfo.AdRewardInfo.class, new ac());
        aoz.put(AdMatrixInfo.InterstitialCardInfo.class, new eq());
        aoz.put(WebCloseStatus.class, new jm());
        aoz.put(AdStyleInfo.AdBrowseInfo.class, new k());
        aoz.put(AdInfo.CallBackStrategyInfo.class, new bh());
        aoz.put(AdMatrixInfo.FullScreenInfo.class, new dm());
        aoz.put(AdMatrixInfo.class, new z());
        aoz.put(AdStyleInfo.PlayDetailInfo.PatchEcInfo.class, new gj());
        aoz.put(StatusInfo.SplashAdInfo.class, new hw());
        aoz.put(AdInfo.ComplianceInfo.class, new br());
        aoz.put(WebViewCommercialMsg.class, new jn());
        aoz.put(AdMatrixInfo.ActivityMiddlePageInfo.class, new g());
        aoz.put(SDKInitMsg.class, new hj());
        aoz.put(com.kwad.sdk.core.report.m.class, new cv());
        aoz.put(FeedSlideConf.class, new de());
        aoz.put(com.kwad.sdk.core.threads.d.class, new ix());
        aoz.put(AdMatrixInfo.EndCardInfo.class, new ct());
        aoz.put(AdStyleInfo.PlayEndInfo.EndTopToolBarInfo.class, new cu());
        aoz.put(AdInfo.UnDownloadRegionConf.class, new jc());
        aoz.put(AdMatrixInfo.InstalledActivateInfo.class, new en());
        aoz.put(HttpDnsInfo.class, new ec());
        aoz.put(AdMatrixInfo.BaseMatrixTemplate.class, new bb());
        aoz.put(AdMatrixInfo.MatrixTemplate.class, new fl());
        aoz.put(PhotoInfo.BaseInfo.class, new ba());
        aoz.put(ABParams.class, new a());
        aoz.put(AdStyleInfo.PlayDetailInfo.DrawAdInfo.class, new cr());
        aoz.put(k.a.C0270a.class, new ih());
        aoz.put(CouponInfo.class, new cb());
        aoz.put(AdMatrixInfo.MatrixTag.class, new fk());
        aoz.put(StatusInfo.SplashStyleControl.class, new Cif());
        aoz.put(AdInfo.AdTrackInfo.class, new aj());
        aoz.put(AdInfo.AdMaterialInfo.class, new y());
        aoz.put(AdProductInfo.class, new ab());
        aoz.put(AdInfo.DownloadSafeInfo.class, new co());
        aoz.put(SceneImpl.class, new hm());
        aoz.put(AdMatrixInfo.SplashInfo.class, new hz());
        aoz.put(AdInfo.class, new r());
        aoz.put(AdMatrixInfo.DownloadTexts.class, new cq());
        aoz.put(AdInfo.AdvertiserInfo.class, new am());
        aoz.put(AdInfo.SmallAppJumpInfo.class, new ht());
        aoz.put(AdMatrixInfo.ActionBarInfoNew.class, new d());
        aoz.put(AdMatrixInfo.PreLandingPageTKInfo.class, new gt());
        aoz.put(NativeAdExtraDataImpl.class, new fp());
        aoz.put(AdInfo.H5Config.class, new dw());
        aoz.put(AdMatrixInfo.SplashEndCardTKInfo.class, new hx());
        aoz.put(AdStyleInfo.ExposeTagInfo.class, new cx());
        aoz.put(AdStyleInfo.PlayDetailInfo.DetailWebCardInfo.class, new ck());
        aoz.put(HttpDnsInfo.IpInfo.class, new et());
        aoz.put(VideoPlayerStatus.class, new ji());
        aoz.put(AdProductInfo.SpikeInfo.class, new hu());
        aoz.put(AdStyleInfo.class, new ah());
        aoz.put(AdInfo.CutRuleInfo.class, new ce());
        aoz.put(com.kwad.sdk.h.a.b.class, new gd());
        aoz.put(AdMatrixInfo.RewardVideoTaskInfo.class, new he());
        aoz.put(AdMatrixInfo.RewardVideoInteractInfo.class, new hd());
        aoz.put(com.kwad.sdk.core.network.j.class, new fw());
        aoz.put(AdInfo.AdPreloadInfo.class, new aa());
        aoz.put(com.kwad.sdk.core.network.k.class, new fx());
        aoz.put(AdInfo.UnDownloadConf.class, new jb());
        aoz.put(AdStyleInfo.PlayDetailInfo.class, new gl());
        aoz.put(AdMatrixInfo.MerchantLiveReservationInfo.class, new fm());
        aoz.put(AdStyleInfo.PlayDetailInfo.DetailTopToolBarInfo.class, new cj());
        aoz.put(AdMatrixInfo.TemplateData.class, new iv());
        aoz.put(AdStyleInfo.PlayDetailInfo.DetailCommonInfo.class, new ci());
        aoz.put(AdMatrixInfo.CycleAggregateInfo.class, new cf());
        aoz.put(AdMatrixInfo.Styles.class, new io());
        aoz.put(PhotoInfo.VideoInfo.class, new jg());
        aoz.put(SplashExtraDataImpl.class, new hy());
        aoz.put(k.a.class, new jq());
        aoz.put(StatusInfo.NativeAdRequestInfo.class, new fr());
        aoz.put(AdInfo.PlayableStyleInfo.class, new gr());
        aoz.put(WebViewLoadMsg.class, new jo());
        aoz.put(AdInfo.AdConversionInfo.class, new l());
        aoz.put(com.kwad.sdk.core.request.model.f.class, new ir());
        aoz.put(AdLabelImpl.class, new u());
        aoz.put(AdMatrixInfo.RotateDegreeInfo.class, new hh());
        aoz.put(AdMatrixInfo.AdDataV2.class, new n());
        aoz.put(URLPackage.class, new ja());
        aoz.put(AdMatrixInfo.ShakeInfo.class, new hn());
        aoz.put(com.kwad.sdk.core.threads.b.class, new iw());
        aoz.put(com.kwad.sdk.h.a.a.class, new gc());
        AP();
    }

    @ForInvoker(methodId = "registerHolder")
    private static void AP() {
        bs.AP();
        bt.AP();
        bu.AP();
        bv.AP();
        bw.AP();
        bx.AP();
        by.AP();
        bz.AP();
        dg.AP();
        dh.AP();
        di.AP();
        dj.AP();
        dk.AP();
        dl.AP();
    }

    public static Map<Class<? extends com.kwad.sdk.core.response.a.a>, com.kwad.sdk.core.d> AQ() {
        return aoz;
    }

    public static com.kwad.sdk.core.d getHolder(Class<? extends com.kwad.sdk.core.response.a.a> cls) {
        return aoz.get(cls);
    }
}
