package com.android.billingclient.api;

import com.android.billingclient.api.c;
/* compiled from: com.android.billingclient:billing@@6.0.1 */
/* loaded from: classes.dex */
public final class f {
    public static final c a;
    public static final c b;
    public static final c c;
    public static final c d;
    public static final c e;
    public static final c f;
    public static final c g;
    public static final c h;
    public static final c i;
    public static final c j;
    public static final c k;
    public static final c l;
    public static final c m;
    public static final c n;
    public static final c o;

    static {
        c.a a2 = c.a();
        a2.a = 3;
        a2.b = "Google Play In-app Billing API version is less than 3";
        a = a2.a();
        c.a a3 = c.a();
        a3.a = 3;
        a3.b = "Google Play In-app Billing API version is less than 9";
        a3.a();
        c.a a4 = c.a();
        a4.a = 3;
        a4.b = "Billing service unavailable on device.";
        b = a4.a();
        c.a a5 = c.a();
        a5.a = 5;
        a5.b = "Client is already in the process of connecting to billing service.";
        c = a5.a();
        c.a a6 = c.a();
        a6.a = 5;
        a6.b = "The list of SKUs can't be empty.";
        a6.a();
        c.a a7 = c.a();
        a7.a = 5;
        a7.b = "SKU type can't be empty.";
        a7.a();
        c.a a8 = c.a();
        a8.a = 5;
        a8.b = "Product type can't be empty.";
        d = a8.a();
        c.a a9 = c.a();
        a9.a = -2;
        a9.b = "Client does not support extra params.";
        e = a9.a();
        c.a a10 = c.a();
        a10.a = 5;
        a10.b = "Invalid purchase token.";
        a10.a();
        c.a a11 = c.a();
        a11.a = 6;
        a11.b = "An internal error occurred.";
        f = a11.a();
        c.a a12 = c.a();
        a12.a = 5;
        a12.b = "SKU can't be null.";
        a12.a();
        c.a a13 = c.a();
        a13.a = 0;
        g = a13.a();
        c.a a14 = c.a();
        a14.a = -1;
        a14.b = "Service connection is disconnected.";
        h = a14.a();
        c.a a15 = c.a();
        a15.a = 2;
        a15.b = "Timeout communicating with service.";
        i = a15.a();
        c.a a16 = c.a();
        a16.a = -2;
        a16.b = "Client does not support subscriptions.";
        j = a16.a();
        c.a a17 = c.a();
        a17.a = -2;
        a17.b = "Client does not support subscriptions update.";
        a17.a();
        c.a a18 = c.a();
        a18.a = -2;
        a18.b = "Client does not support get purchase history.";
        k = a18.a();
        c.a a19 = c.a();
        a19.a = -2;
        a19.b = "Client does not support price change confirmation.";
        a19.a();
        c.a a20 = c.a();
        a20.a = -2;
        a20.b = "Play Store version installed does not support cross selling products.";
        a20.a();
        c.a a21 = c.a();
        a21.a = -2;
        a21.b = "Client does not support multi-item purchases.";
        l = a21.a();
        c.a a22 = c.a();
        a22.a = -2;
        a22.b = "Client does not support offer_id_token.";
        m = a22.a();
        c.a a23 = c.a();
        a23.a = -2;
        a23.b = "Client does not support ProductDetails.";
        n = a23.a();
        c.a a24 = c.a();
        a24.a = -2;
        a24.b = "Client does not support in-app messages.";
        a24.a();
        c.a a25 = c.a();
        a25.a = -2;
        a25.b = "Client does not support alternative billing.";
        a25.a();
        c.a a26 = c.a();
        a26.a = 5;
        a26.b = "Unknown feature";
        a26.a();
        c.a a27 = c.a();
        a27.a = -2;
        a27.b = "Play Store version installed does not support get billing config.";
        a27.a();
        c.a a28 = c.a();
        a28.a = -2;
        a28.b = "Query product details with serialized docid is not supported.";
        a28.a();
        c.a a29 = c.a();
        a29.a = 4;
        a29.b = "Item is unavailable for purchase.";
        o = a29.a();
        c.a a30 = c.a();
        a30.a = -2;
        a30.b = "Query product details with developer specified account is not supported.";
        a30.a();
    }
}
