package com.vungle.publisher.inject;

import android.content.Context;
import android.content.SharedPreferences;
import android.media.AudioManager;
import android.net.ConnectivityManager;
import android.net.wifi.WifiManager;
import android.telephony.TelephonyManager;
import android.view.WindowManager;
import com.vungle.publisher.AdConfig;
import com.vungle.publisher.AdConfig_Factory;
import com.vungle.publisher.Cdo;
import com.vungle.publisher.Cif;
import com.vungle.publisher.InitializationEventListener;
import com.vungle.publisher.InitializationEventListener_Factory;
import com.vungle.publisher.InitializationEventListener_InitialConfigUpdatedEventListener_Factory;
import com.vungle.publisher.InitializationEventListener_InitialConfigUpdatedEventListener_MembersInjector;
import com.vungle.publisher.InitializationEventListener_MembersInjector;
import com.vungle.publisher.VungleAdActivity;
import com.vungle.publisher.VungleAdActivity_MembersInjector;
import com.vungle.publisher.VunglePubBase;
import com.vungle.publisher.VunglePubBase_MembersInjector;
import com.vungle.publisher.bd;
import com.vungle.publisher.be;
import com.vungle.publisher.bf;
import com.vungle.publisher.bw;
import com.vungle.publisher.bx;
import com.vungle.publisher.by;
import com.vungle.publisher.bz;
import com.vungle.publisher.ca;
import com.vungle.publisher.cb;
import com.vungle.publisher.cc;
import com.vungle.publisher.cd;
import com.vungle.publisher.cf;
import com.vungle.publisher.cg;
import com.vungle.publisher.ch;
import com.vungle.publisher.ci;
import com.vungle.publisher.ck;
import com.vungle.publisher.cl;
import com.vungle.publisher.cn;
import com.vungle.publisher.co;
import com.vungle.publisher.cp;
import com.vungle.publisher.cq;
import com.vungle.publisher.cr;
import com.vungle.publisher.cs;
import com.vungle.publisher.ct;
import com.vungle.publisher.cu;
import com.vungle.publisher.cv;
import com.vungle.publisher.cw;
import com.vungle.publisher.cx;
import com.vungle.publisher.cz;
import com.vungle.publisher.db;
import com.vungle.publisher.dc;
import com.vungle.publisher.dd;
import com.vungle.publisher.de;
import com.vungle.publisher.df;
import com.vungle.publisher.dg;
import com.vungle.publisher.dh;
import com.vungle.publisher.di;
import com.vungle.publisher.dj;
import com.vungle.publisher.dk;
import com.vungle.publisher.dl;
import com.vungle.publisher.dm;
import com.vungle.publisher.dn;
import com.vungle.publisher.dt;
import com.vungle.publisher.du;
import com.vungle.publisher.dv;
import com.vungle.publisher.dw;
import com.vungle.publisher.dx;
import com.vungle.publisher.dy;
import com.vungle.publisher.dz;
import com.vungle.publisher.eb;
import com.vungle.publisher.ec;
import com.vungle.publisher.ed;
import com.vungle.publisher.ee;
import com.vungle.publisher.ef;
import com.vungle.publisher.ek;
import com.vungle.publisher.el;
import com.vungle.publisher.em;
import com.vungle.publisher.en;
import com.vungle.publisher.env.AndroidDevice;
import com.vungle.publisher.env.WrapperFramework;
import com.vungle.publisher.eo;
import com.vungle.publisher.ep;
import com.vungle.publisher.eq;
import com.vungle.publisher.er;
import com.vungle.publisher.es;
import com.vungle.publisher.et;
import com.vungle.publisher.eu;
import com.vungle.publisher.ev;
import com.vungle.publisher.ew;
import com.vungle.publisher.ex;
import com.vungle.publisher.ey;
import com.vungle.publisher.ez;
import com.vungle.publisher.fa;
import com.vungle.publisher.fb;
import com.vungle.publisher.fc;
import com.vungle.publisher.fd;
import com.vungle.publisher.fe;
import com.vungle.publisher.ff;
import com.vungle.publisher.fg;
import com.vungle.publisher.fh;
import com.vungle.publisher.fi;
import com.vungle.publisher.fj;
import com.vungle.publisher.fk;
import com.vungle.publisher.fl;
import com.vungle.publisher.fm;
import com.vungle.publisher.fn;
import com.vungle.publisher.fo;
import com.vungle.publisher.fp;
import com.vungle.publisher.fq;
import com.vungle.publisher.fr;
import com.vungle.publisher.fs;
import com.vungle.publisher.ft;
import com.vungle.publisher.fu;
import com.vungle.publisher.fv;
import com.vungle.publisher.fw;
import com.vungle.publisher.fx;
import com.vungle.publisher.fy;
import com.vungle.publisher.fz;
import com.vungle.publisher.ga;
import com.vungle.publisher.gb;
import com.vungle.publisher.gc;
import com.vungle.publisher.gf;
import com.vungle.publisher.gg;
import com.vungle.publisher.gh;
import com.vungle.publisher.gi;
import com.vungle.publisher.gk;
import com.vungle.publisher.gl;
import com.vungle.publisher.gm;
import com.vungle.publisher.gn;
import com.vungle.publisher.go;
import com.vungle.publisher.gp;
import com.vungle.publisher.gq;
import com.vungle.publisher.gr;
import com.vungle.publisher.gs;
import com.vungle.publisher.gt;
import com.vungle.publisher.gu;
import com.vungle.publisher.gv;
import com.vungle.publisher.gw;
import com.vungle.publisher.gx;
import com.vungle.publisher.gy;
import com.vungle.publisher.gz;
import com.vungle.publisher.ha;
import com.vungle.publisher.hb;
import com.vungle.publisher.hc;
import com.vungle.publisher.hd;
import com.vungle.publisher.he;
import com.vungle.publisher.hg;
import com.vungle.publisher.hh;
import com.vungle.publisher.hi;
import com.vungle.publisher.hj;
import com.vungle.publisher.hk;
import com.vungle.publisher.hl;
import com.vungle.publisher.hm;
import com.vungle.publisher.hn;
import com.vungle.publisher.ho;
import com.vungle.publisher.hq;
import com.vungle.publisher.hr;
import com.vungle.publisher.hs;
import com.vungle.publisher.ht;
import com.vungle.publisher.hu;
import com.vungle.publisher.hv;
import com.vungle.publisher.hw;
import com.vungle.publisher.hx;
import com.vungle.publisher.hy;
import com.vungle.publisher.hz;
import com.vungle.publisher.ia;
import com.vungle.publisher.ib;
import com.vungle.publisher.ic;
import com.vungle.publisher.id;
import com.vungle.publisher.ie;
import com.vungle.publisher.ig;
import com.vungle.publisher.ih;
import com.vungle.publisher.ii;
import com.vungle.publisher.ij;
import com.vungle.publisher.ik;
import com.vungle.publisher.il;
import com.vungle.publisher.im;
import com.vungle.publisher.image.AssetBitmapFactory;
import com.vungle.publisher.in;
import com.vungle.publisher.io;
import com.vungle.publisher.ip;
import com.vungle.publisher.iq;
import com.vungle.publisher.ir;
import com.vungle.publisher.is;
import com.vungle.publisher.it;
import com.vungle.publisher.iu;
import com.vungle.publisher.iv;
import com.vungle.publisher.iw;
import com.vungle.publisher.ix;
import com.vungle.publisher.iy;
import com.vungle.publisher.iz;
import com.vungle.publisher.ja;
import com.vungle.publisher.jb;
import com.vungle.publisher.jc;
import com.vungle.publisher.jd;
import com.vungle.publisher.jn;
import com.vungle.publisher.jo;
import com.vungle.publisher.jp;
import com.vungle.publisher.jq;
import com.vungle.publisher.jr;
import com.vungle.publisher.js;
import com.vungle.publisher.jt;
import com.vungle.publisher.ju;
import com.vungle.publisher.jv;
import com.vungle.publisher.jw;
import com.vungle.publisher.jx;
import com.vungle.publisher.jy;
import com.vungle.publisher.jz;
import com.vungle.publisher.ka;
import com.vungle.publisher.kb;
import com.vungle.publisher.kc;
import com.vungle.publisher.kd;
import com.vungle.publisher.ke;
import com.vungle.publisher.kf;
import com.vungle.publisher.kg;
import com.vungle.publisher.kh;
import com.vungle.publisher.ki;
import com.vungle.publisher.kj;
import com.vungle.publisher.kk;
import com.vungle.publisher.kl;
import com.vungle.publisher.km;
import com.vungle.publisher.kn;
import com.vungle.publisher.ko;
import com.vungle.publisher.kp;
import com.vungle.publisher.kq;
import com.vungle.publisher.kr;
import com.vungle.publisher.ks;
import com.vungle.publisher.kt;
import com.vungle.publisher.ku;
import com.vungle.publisher.kv;
import com.vungle.publisher.kw;
import com.vungle.publisher.kx;
import com.vungle.publisher.ky;
import com.vungle.publisher.kz;
import com.vungle.publisher.la;
import com.vungle.publisher.lb;
import com.vungle.publisher.lc;
import com.vungle.publisher.ld;
import com.vungle.publisher.le;
import com.vungle.publisher.lf;
import com.vungle.publisher.lg;
import com.vungle.publisher.lh;
import com.vungle.publisher.li;
import com.vungle.publisher.lj;
import com.vungle.publisher.lk;
import com.vungle.publisher.ll;
import com.vungle.publisher.lm;
import com.vungle.publisher.ln;
import com.vungle.publisher.lo;
import com.vungle.publisher.lp;
import com.vungle.publisher.lq;
import com.vungle.publisher.lr;
import com.vungle.publisher.lw;
import com.vungle.publisher.lx;
import com.vungle.publisher.ly;
import com.vungle.publisher.lz;
import com.vungle.publisher.m;
import com.vungle.publisher.ma;
import com.vungle.publisher.mb;
import com.vungle.publisher.mc;
import com.vungle.publisher.md;
import com.vungle.publisher.mg;
import com.vungle.publisher.mh;
import com.vungle.publisher.mi;
import com.vungle.publisher.mj;
import com.vungle.publisher.mn;
import com.vungle.publisher.mo;
import com.vungle.publisher.mq;
import com.vungle.publisher.mu;
import com.vungle.publisher.mv;
import com.vungle.publisher.mw;
import com.vungle.publisher.mx;
import com.vungle.publisher.my;
import com.vungle.publisher.na;
import com.vungle.publisher.nb;
import com.vungle.publisher.nc;
import com.vungle.publisher.nd;
import com.vungle.publisher.ne;
import com.vungle.publisher.nf;
import com.vungle.publisher.ng;
import com.vungle.publisher.nh;
import com.vungle.publisher.nk;
import com.vungle.publisher.nm;
import com.vungle.publisher.nn;
import com.vungle.publisher.no;
import com.vungle.publisher.np;
import com.vungle.publisher.nq;
import com.vungle.publisher.nr;
import com.vungle.publisher.ns;
import com.vungle.publisher.nu;
import com.vungle.publisher.nv;
import com.vungle.publisher.nw;
import com.vungle.publisher.nx;
import com.vungle.publisher.ny;
import com.vungle.publisher.nz;
import com.vungle.publisher.ob;
import com.vungle.publisher.oc;
import com.vungle.publisher.od;
import com.vungle.publisher.oe;
import com.vungle.publisher.of;
import com.vungle.publisher.og;
import com.vungle.publisher.oh;
import com.vungle.publisher.oi;
import com.vungle.publisher.oj;
import com.vungle.publisher.ok;
import com.vungle.publisher.ol;
import com.vungle.publisher.on;
import com.vungle.publisher.oo;
import com.vungle.publisher.op;
import com.vungle.publisher.ou;
import com.vungle.publisher.ov;
import com.vungle.publisher.ow;
import com.vungle.publisher.ox;
import com.vungle.publisher.oy;
import com.vungle.publisher.oz;
import com.vungle.publisher.pa;
import com.vungle.publisher.pb;
import com.vungle.publisher.pc;
import com.vungle.publisher.pd;
import com.vungle.publisher.pe;
import com.vungle.publisher.pj;
import com.vungle.publisher.pu;
import com.vungle.publisher.pv;
import com.vungle.publisher.pw;
import com.vungle.publisher.px;
import com.vungle.publisher.py;
import com.vungle.publisher.qb;
import com.vungle.publisher.qc;
import com.vungle.publisher.qd;
import com.vungle.publisher.qe;
import com.vungle.publisher.qg;
import com.vungle.publisher.qh;
import com.vungle.publisher.qo;
import com.vungle.publisher.qp;
import com.vungle.publisher.qq;
import com.vungle.publisher.qw;
import com.vungle.publisher.qz;
import com.vungle.publisher.rb;
import com.vungle.publisher.rc;
import com.vungle.publisher.rd;
import com.vungle.publisher.re;
import com.vungle.publisher.rf;
import com.vungle.publisher.rg;
import com.vungle.publisher.ri;
import com.vungle.publisher.rj;
import com.vungle.publisher.rk;
import com.vungle.publisher.rl;
import com.vungle.publisher.rm;
import com.vungle.publisher.rn;
import com.vungle.publisher.ro;
import com.vungle.publisher.rp;
import com.vungle.publisher.rq;
import com.vungle.publisher.rr;
import com.vungle.publisher.rs;
import com.vungle.publisher.rt;
import com.vungle.publisher.rv;
import com.vungle.publisher.rw;
import com.vungle.publisher.rz;
import com.vungle.publisher.sa;
import com.vungle.publisher.sb;
import com.vungle.publisher.sc;
import com.vungle.publisher.sd;
import com.vungle.publisher.sv;
import com.vungle.publisher.sw;
import com.vungle.publisher.sx;
import com.vungle.publisher.sz;
import com.vungle.publisher.ta;
import com.vungle.publisher.tb;
import com.vungle.publisher.tc;
import com.vungle.publisher.te;
import com.vungle.publisher.tf;
import com.vungle.publisher.tg;
import com.vungle.publisher.th;
import com.vungle.publisher.ti;
import com.vungle.publisher.tj;
import com.vungle.publisher.tl;
import com.vungle.publisher.tm;
import com.vungle.publisher.tn;
import com.vungle.publisher.to;
import com.vungle.publisher.tp;
import com.vungle.publisher.ts;
import com.vungle.publisher.tt;
import com.vungle.publisher.tu;
import com.vungle.publisher.tv;
import com.vungle.publisher.tw;
import com.vungle.publisher.ty;
import com.vungle.publisher.tz;
import com.vungle.publisher.ua;
import com.vungle.publisher.ub;
import com.vungle.publisher.uc;
import com.vungle.publisher.ud;
import com.vungle.publisher.ue;
import com.vungle.publisher.uf;
import com.vungle.publisher.ug;
import com.vungle.publisher.uh;
import com.vungle.publisher.ui;
import com.vungle.publisher.uk;
import com.vungle.publisher.uo;
import com.vungle.publisher.up;
import com.vungle.publisher.uq;
import com.vungle.publisher.ur;
import com.vungle.publisher.us;
import com.vungle.publisher.uv;
import com.vungle.publisher.uw;
import com.vungle.publisher.ux;
import com.vungle.publisher.uy;
import com.vungle.publisher.uz;
import com.vungle.publisher.va;
import com.vungle.publisher.vb;
import com.vungle.publisher.vc;
import com.vungle.publisher.vq;
import com.vungle.publisher.vr;
import com.vungle.publisher.vu;
import com.vungle.publisher.vv;
import com.vungle.publisher.vw;
import com.vungle.publisher.vx;
import com.vungle.publisher.wb;
import com.vungle.publisher.wd;
import com.vungle.publisher.we;
import com.vungle.publisher.wf;
import com.vungle.publisher.wg;
import com.vungle.publisher.wh;
import com.vungle.publisher.wi;
import com.vungle.publisher.wj;
import com.vungle.publisher.wk;
import com.vungle.publisher.wl;
import com.vungle.publisher.wm;
import com.vungle.publisher.wn;
import com.vungle.publisher.wo;
import com.vungle.publisher.wq;
import com.vungle.publisher.wr;
import com.vungle.publisher.ws;
import com.vungle.publisher.wt;
import com.vungle.publisher.ww;
import com.vungle.publisher.wx;
import com.vungle.publisher.wz;
import com.vungle.publisher.xa;
import com.vungle.publisher.xb;
import com.vungle.publisher.xc;
import com.vungle.publisher.xd;
import com.vungle.publisher.xe;
import com.vungle.publisher.xf;
import com.vungle.publisher.xg;
import com.vungle.publisher.xo;
import com.vungle.publisher.xp;
import com.vungle.publisher.xq;
import com.vungle.publisher.xw;
import com.vungle.publisher.xx;
import com.vungle.publisher.xy;
import com.vungle.publisher.yb;
import com.vungle.publisher.yc;
import com.vungle.publisher.yd;
import com.vungle.publisher.yf;
import com.vungle.publisher.yg;
import com.vungle.publisher.yh;
import com.vungle.publisher.yi;
import com.vungle.publisher.yk;
import com.vungle.publisher.yl;
import com.vungle.publisher.ym;
import com.vungle.publisher.yn;
import com.vungle.publisher.yo;
import com.vungle.publisher.yp;
import com.vungle.publisher.yq;
import com.vungle.publisher.yr;
import com.vungle.publisher.ys;
import com.vungle.publisher.yt;
import com.vungle.publisher.yu;
import com.vungle.publisher.yv;
import com.vungle.publisher.yw;
import com.vungle.publisher.zc;
import com.vungle.publisher.zd;
import com.vungle.publisher.zf;
import com.vungle.publisher.zg;
import com.vungle.publisher.zh;
import com.vungle.publisher.zl;
import com.vungle.publisher.zm;
import com.vungle.publisher.zo;
import com.vungle.publisher.zq;
import com.vungle.publisher.zr;
import dagger.MembersInjector;
import dagger.internal.DelegateFactory;
import dagger.internal.DoubleCheck;
import dagger.internal.MembersInjectors;
import dagger.internal.Preconditions;
import javax.inject.Provider;
/* loaded from: classes4.dex */
public final class r implements w {
    static final /* synthetic */ boolean a;
    private MembersInjector<AndroidDevice> A;
    private Provider<AndroidDevice> B;
    private Provider<com.vungle.publisher.env.i> C;
    private MembersInjector<lp> D;
    private Provider<lp> E;
    private Provider<ConnectivityManager> F;
    private Provider<TelephonyManager> G;
    private MembersInjector<sv> H;
    private Provider<sv> I;
    private Provider<sz> J;
    private MembersInjector<ta> K;
    private Provider<ta> L;
    private MembersInjector<com.vungle.publisher.env.k> M;
    private Provider<com.vungle.publisher.env.k> N;
    private Provider<Class> O;
    private Provider<Class> P;
    private Provider<Class> Q;
    private MembersInjector<com.vungle.publisher.log.d> R;
    private Provider<com.vungle.publisher.log.d> S;
    private MembersInjector<com.vungle.publisher.log.a> T;
    private Provider<com.vungle.publisher.log.a> U;
    private MembersInjector<com.vungle.publisher.log.g> V;
    private Provider<com.vungle.publisher.log.g> W;
    private MembersInjector X;
    private Provider Y;
    private MembersInjector<ct> Z;
    private MembersInjector aA;
    private Provider aB;
    private MembersInjector aC;
    private Provider aD;
    private MembersInjector<df> aE;
    private Provider<df> aF;
    private MembersInjector<df.a> aG;
    private Provider<df.a> aH;
    private Provider<lb> aI;
    private MembersInjector<lb.a> aJ;
    private Provider<lb.a> aK;
    private MembersInjector<em> aL;
    private Provider<em> aM;
    private MembersInjector<em.a> aN;
    private Provider<em.a> aO;
    private MembersInjector<el> aP;
    private Provider<el> aQ;
    private MembersInjector<ek> aR;
    private Provider<ek> aS;
    private MembersInjector aT;
    private Provider aU;
    private MembersInjector<eb.c> aV;
    private Provider<eb.c> aW;
    private MembersInjector<hk> aX;
    private Provider<hk> aY;
    private MembersInjector<hk.a> aZ;
    private Provider<ct> aa;
    private MembersInjector<ct.a> ab;
    private Provider<ct.a> ac;
    private MembersInjector<hr> ad;
    private Provider<hr> ae;
    private Provider<m.a> af;
    private MembersInjector<hq> ag;
    private Provider<hq> ah;
    private MembersInjector ai;
    private Provider aj;
    private MembersInjector<im> ak;
    private Provider<im> al;
    private MembersInjector<hs> am;
    private Provider<hs> an;
    private MembersInjector ao;
    private Provider ap;
    private MembersInjector<im.a> aq;
    private Provider<im.a> ar;
    private MembersInjector<hr.a> as;
    private Provider<hr.a> at;
    private MembersInjector au;
    private Provider av;
    private MembersInjector<co> aw;
    private Provider<co> ax;
    private MembersInjector<co.a> ay;
    private Provider<co.a> az;
    private Provider<qg> b;
    private Provider<fg> bA;
    private MembersInjector bB;
    private Provider bC;
    private MembersInjector<fg.a> bD;
    private Provider<fg.a> bE;
    private MembersInjector<hx> bF;
    private Provider<hx> bG;
    private MembersInjector<id> bH;
    private Provider<id> bI;
    private MembersInjector bJ;
    private Provider bK;
    private MembersInjector bL;
    private Provider bM;
    private MembersInjector<ic> bN;
    private Provider<ic> bO;
    private MembersInjector<ic.a> bP;
    private Provider<ic.a> bQ;
    private MembersInjector<jn> bR;
    private Provider<jn> bS;
    private MembersInjector<dk> bT;
    private Provider<dk> bU;
    private MembersInjector<iz> bV;
    private Provider<iz> bW;
    private MembersInjector<iz.a> bX;
    private Provider<iz.a> bY;
    private MembersInjector bZ;
    private Provider<hk.a> ba;
    private MembersInjector<er> bb;
    private Provider<er> bc;
    private MembersInjector<er.a> bd;
    private Provider<er.a> be;
    private MembersInjector<dw.a> bf;
    private Provider<dw.a> bg;
    private MembersInjector<fq> bh;
    private Provider<fq> bi;
    private MembersInjector<ew> bj;
    private Provider<ew> bk;
    private MembersInjector bl;
    private Provider bm;
    private MembersInjector<fq.a> bn;
    private Provider<fq.a> bo;
    private MembersInjector<el.a> bp;
    private Provider<el.a> bq;
    private MembersInjector<fb> br;
    private Provider<fb> bs;
    private MembersInjector<fh> bt;
    private Provider<fh> bu;
    private MembersInjector bv;
    private Provider bw;
    private MembersInjector bx;
    private Provider by;
    private MembersInjector<fg> bz;
    private Provider<bz> c;
    private Provider<kd.a> cA;
    private MembersInjector<ki> cB;
    private Provider<ki> cC;
    private MembersInjector<ki.a> cD;
    private Provider<ki.a> cE;
    private Provider<li> cF;
    private MembersInjector<li.a> cG;
    private Provider<li.a> cH;
    private MembersInjector<gk> cI;
    private Provider<gk> cJ;
    private MembersInjector<gl> cK;
    private Provider<gl> cL;
    private MembersInjector<gl.a> cM;
    private Provider<gl.a> cN;
    private MembersInjector<gk.a> cO;
    private Provider<gk.a> cP;
    private MembersInjector<gq> cQ;
    private Provider<gq> cR;
    private MembersInjector<gw> cS;
    private Provider<gw> cT;
    private MembersInjector<gw.a> cU;
    private Provider<gw.a> cV;
    private MembersInjector<gq.a> cW;
    private Provider<gq.a> cX;
    private MembersInjector<gv> cY;
    private Provider<gv> cZ;
    private Provider ca;
    private MembersInjector<jt> cb;
    private Provider<jt> cc;
    private MembersInjector<jt.a> cd;
    private Provider<jt.a> ce;
    private MembersInjector<jo> cf;
    private Provider<jo> cg;
    private MembersInjector<jo.a> ch;
    private Provider<jo.a> ci;
    private MembersInjector<jy> cj;
    private Provider<jy> ck;
    private MembersInjector<jy.a> cl;
    private Provider<jy.a> cm;
    private MembersInjector<ks> cn;
    private Provider<ks> co;
    private MembersInjector<ks.a> cp;
    private Provider<ks.a> cq;
    private MembersInjector<jn.a> cr;
    private Provider<jn.a> cs;
    private MembersInjector<kd> ct;
    private Provider<kd> cu;
    private MembersInjector<kj> cv;
    private Provider<kj> cw;
    private MembersInjector<kj.a> cx;
    private Provider<kj.a> cy;
    private MembersInjector<kd.a> cz;
    private Provider<zl> d;
    private MembersInjector<tw.a> dA;
    private Provider<tw.a> dB;
    private MembersInjector<ts.a> dC;
    private Provider<ts.a> dD;
    private MembersInjector<ue> dE;
    private Provider<ue> dF;
    private MembersInjector<uz> dG;
    private Provider<uz> dH;
    private Provider<th.a> dI;
    private MembersInjector<xy> dJ;
    private Provider<xy> dK;
    private MembersInjector<xq> dL;
    private Provider<xq> dM;
    private MembersInjector<uw> dN;
    private Provider<uw> dO;
    private MembersInjector<wg.a> dP;
    private Provider<wg.a> dQ;
    private MembersInjector<wj.a> dR;
    private Provider<wj.a> dS;
    private Provider<xb.a> dT;
    private Provider<wz.a> dU;
    private Provider<vu> dV;
    private MembersInjector dW;
    private Provider dX;
    private MembersInjector<wr.a> dY;
    private Provider<wr.a> dZ;
    private MembersInjector<gv.a> da;
    private Provider<gv.a> db;
    private MembersInjector<cz.b> dc;
    private Provider<cz.b> dd;

    /* renamed from: de  reason: collision with root package name */
    private MembersInjector<yk> f13de;
    private Provider<yk> df;
    private MembersInjector<zf> dg;
    private Provider<zf> dh;
    private Provider di;
    private Provider dj;
    private MembersInjector dk;
    private Provider dl;
    private MembersInjector<wm.a> dm;
    private Provider<wm.a> dn;

    /* renamed from: do  reason: not valid java name */
    private Provider<String> f3do;
    private Provider<yd> dp;
    private MembersInjector<vc> dq;
    private Provider<vc> dr;
    private Provider<AdConfig> ds;
    private MembersInjector<com.vungle.publisher.u> dt;
    private Provider<com.vungle.publisher.u> du;
    private MembersInjector<cn.b> dv;
    private Provider<cn.b> dw;
    private MembersInjector<eb.b> dx;
    private Provider<eb.b> dy;
    private Provider<uh> dz;
    private Provider<Context> e;
    private Provider<uo.a> eA;
    private MembersInjector<te> eB;
    private Provider<te> eC;
    private MembersInjector<tn> eD;
    private Provider<tn> eE;
    private MembersInjector<uq> eF;
    private Provider<uq> eG;
    private MembersInjector<tj> eH;
    private Provider<tj> eI;
    private MembersInjector<ys> eJ;
    private Provider<ys> eK;
    private MembersInjector<ys.a> eL;
    private Provider<ys.a> eM;
    private Provider<mq> eN;
    private MembersInjector<mv> eO;
    private Provider<mv> eP;
    private MembersInjector<AssetBitmapFactory> eQ;
    private Provider<AssetBitmapFactory> eR;
    private MembersInjector<zo> eS;
    private Provider<zo> eT;
    private MembersInjector<og.a> eU;
    private Provider<og.a> eV;
    private MembersInjector<oj.a> eW;
    private Provider<oj.a> eX;
    private MembersInjector<bd.a> eY;
    private Provider<bd.a> eZ;
    private MembersInjector<yg.a> ea;
    private Provider<yg.a> eb;
    private MembersInjector<xd> ec;
    private Provider<xd> ed;
    private MembersInjector<wd.a> ee;
    private Provider<wd.a> ef;
    private MembersInjector<xg> eg;
    private Provider<xg> eh;
    private MembersInjector<com.vungle.publisher.c> ei;
    private Provider<com.vungle.publisher.c> ej;
    private MembersInjector<pj> ek;
    private Provider<pj> el;
    private MembersInjector<pj.a> em;
    private Provider<pj.a> en;
    private MembersInjector<com.vungle.publisher.env.o> eo;
    private Provider<com.vungle.publisher.env.o> ep;
    private Provider<String> eq;
    private MembersInjector<com.vungle.publisher.env.r> er;
    private Provider<com.vungle.publisher.env.r> es;
    private Provider<zc> et;
    private MembersInjector<oy.a> eu;
    private Provider<oy.a> ev;
    private MembersInjector<oy.a.C0334a> ew;
    private Provider<oy.a.C0334a> ex;
    private MembersInjector<ub> ey;
    private Provider<ub> ez;
    private Provider<String> f;
    private MembersInjector<rz> fA;
    private Provider<rz> fB;
    private MembersInjector<rz.a> fC;
    private Provider<rz.a> fD;
    private MembersInjector<rr> fE;
    private Provider<rr> fF;
    private Provider<rv.a> fG;
    private MembersInjector<rg> fH;
    private Provider<rg> fI;
    private MembersInjector<rg.a> fJ;
    private Provider<rg.a> fK;
    private Provider<rd> fL;
    private MembersInjector<rf.a> fM;
    private Provider<rf.a> fN;
    private MembersInjector<my.b> fO;
    private Provider<my.b> fP;
    private MembersInjector<my.b.a> fQ;
    private Provider<my.b.a> fR;
    private MembersInjector<ro.a> fS;
    private Provider<ro.a> fT;
    private MembersInjector<my> fU;
    private Provider<my> fV;
    private MembersInjector<my.a> fW;
    private Provider<my.a> fX;
    private MembersInjector<nk.a> fY;
    private Provider<nk.a> fZ;
    private MembersInjector<cb> fa;
    private Provider<cb> fb;
    private MembersInjector<op> fc;
    private Provider<op> fd;
    private MembersInjector<op.a> fe;
    private Provider<op.a> ff;
    private MembersInjector<lf.b> fg;
    private Provider<lf.b> fh;
    private Provider<mc> fi;
    private MembersInjector<lz> fj;
    private Provider<lz> fk;
    private MembersInjector<lw> fl;
    private Provider<lw> fm;
    private MembersInjector fn;
    private Provider fo;
    private MembersInjector<ob> fp;
    private Provider<ob> fq;
    private MembersInjector<ob.a> fr;
    private Provider<ob.a> fs;
    private MembersInjector<oy> ft;
    private Provider<oy> fu;
    private MembersInjector<yn> fv;
    private Provider<yn> fw;
    private MembersInjector<yn.a> fx;
    private Provider<yn.a> fy;
    private Provider<rb> fz;
    private Provider<String> g;
    private MembersInjector<nk.a.C0332a> ga;
    private Provider<nk.a.C0332a> gb;
    private MembersInjector<nk> gc;
    private Provider<nk> gd;
    private MembersInjector<ns.a> ge;
    private Provider<ns.a> gf;
    private MembersInjector<ns.a.C0333a> gg;
    private Provider<ns.a.C0333a> gh;
    private MembersInjector<ns> gi;
    private Provider<ns> gj;
    private MembersInjector<mg.a> gk;
    private Provider<mg.a> gl;
    private MembersInjector<VungleAdActivity> gm;
    private MembersInjector gn;
    private Provider go;
    private MembersInjector<InitializationEventListener> gp;
    private Provider<InitializationEventListener> gq;
    private MembersInjector<py> gr;
    private Provider<py> gs;
    private MembersInjector<py.a> gt;
    private Provider<py.a> gu;
    private MembersInjector<mj.a> gv;
    private Provider<mj.a> gw;
    private MembersInjector<VunglePubBase> gx;
    private MembersInjector<qw> gy;
    private MembersInjector<qo> h;
    private Provider<qo> i;
    private Provider<WrapperFramework> j;
    private Provider<com.vungle.publisher.env.n> k;
    private MembersInjector<bw> l;
    private Provider<bw> m;
    private MembersInjector<ci> n;
    private Provider<ci> o;
    private MembersInjector<cf> p;
    private Provider<cf> q;
    private Provider<AudioManager> r;
    private MembersInjector<lm> s;
    private Provider<lm> t;
    private Provider<WindowManager> u;
    private Provider<SharedPreferences> v;
    private Provider<WifiManager> w;
    private MembersInjector<com.vungle.publisher.env.a> x;
    private Provider<com.vungle.publisher.env.a> y;
    private Provider<AndroidDevice.DeviceIdStrategy> z;

    static {
        a = !r.class.desiredAssertionStatus();
    }

    private r(a aVar) {
        if (!a && aVar == null) {
            throw new AssertionError();
        }
        a(aVar);
        b(aVar);
        c(aVar);
        d(aVar);
    }

    public static a a() {
        return new a();
    }

    private void a(a aVar) {
        this.b = DoubleCheck.provider(qh.b());
        this.c = DoubleCheck.provider(ca.b());
        this.d = DoubleCheck.provider(zm.b());
        this.e = c.a(aVar.a);
        this.f = b.a(aVar.a, this.e);
        this.g = k.a(aVar.a, this.e);
        this.h = qq.a(this.f, this.g);
        this.i = DoubleCheck.provider(qp.a(this.h));
        this.j = p.a(aVar.a);
        this.k = DoubleCheck.provider(l.a(aVar.a, this.e, this.j));
        this.l = by.a(this.d);
        this.m = DoubleCheck.provider(bx.a(this.l));
        this.n = cl.a(this.i, this.b, this.k, this.m);
        this.o = DoubleCheck.provider(ck.a(this.n, this.e));
        this.p = ch.a(this.e, this.o, this.k);
        this.q = DoubleCheck.provider(cg.a(this.p));
        this.r = DoubleCheck.provider(d.a(aVar.a, this.e));
        this.s = lo.a(this.r);
        this.t = DoubleCheck.provider(ln.a(this.s));
        this.u = o.a(aVar.a, this.e);
        this.v = g.a(aVar.a, this.e);
        this.w = v.a(aVar.b, this.e);
        this.x = com.vungle.publisher.env.c.a(this.e, this.b, this.m, this.w);
        this.y = DoubleCheck.provider(com.vungle.publisher.env.b.a(this.x));
        this.z = DoubleCheck.provider(u.a(aVar.b, this.y));
        this.A = com.vungle.publisher.env.g.a(this.t, this.u, this.e, this.v, this.z, this.f);
        this.B = DoubleCheck.provider(com.vungle.publisher.env.f.a(this.A));
        this.C = DoubleCheck.provider(f.a(aVar.a, this.B));
        this.D = lr.a(this.e, this.b);
        this.E = DoubleCheck.provider(lq.a(this.D));
        this.F = e.a(aVar.a, this.e);
        this.G = m.a(aVar.a, this.e);
        this.L = new DelegateFactory();
        this.H = sx.a(this.F, this.L, this.G);
        this.I = DoubleCheck.provider(sw.a(this.H));
        this.J = DoubleCheck.provider(j.a(aVar.a, this.I));
        this.K = tc.a(this.e, this.J, this.b, this.F);
        this.L = DoubleCheck.provider(tb.a(this.K));
        ((DelegateFactory) this.L).setDelegatedProvider(this.L);
        this.M = com.vungle.publisher.env.m.a(this.b, this.v);
        this.N = DoubleCheck.provider(com.vungle.publisher.env.l.a(this.M));
        this.O = n.a(aVar.a);
        this.P = i.a(aVar.a);
        this.Q = h.a(aVar.a);
        this.es = new DelegateFactory();
        this.R = com.vungle.publisher.log.f.a(this.es);
        this.S = DoubleCheck.provider(com.vungle.publisher.log.e.a(this.R));
        this.T = com.vungle.publisher.log.c.a(this.es, this.k);
        this.U = DoubleCheck.provider(com.vungle.publisher.log.b.a(this.T));
        this.ep = new DelegateFactory();
        this.V = com.vungle.publisher.log.i.a(this.e, this.S, this.U, this.B, this.I, this.ep);
        this.W = DoubleCheck.provider(com.vungle.publisher.log.h.a(this.V));
        this.X = com.vungle.publisher.j.a(this.b, this.W);
        this.Y = DoubleCheck.provider(com.vungle.publisher.i.a(this.X));
        this.ac = new DelegateFactory();
        this.Z = cx.a(this.o, this.ac);
        this.aa = cu.a(this.Z);
        this.ab = cw.a(this.o, this.aa);
        this.ac = cv.a(this.ab);
        ((DelegateFactory) this.ac).setDelegatedProvider(this.ac);
        this.at = new DelegateFactory();
        this.ad = iu.a(this.o, this.b, this.at);
        this.ae = ir.a(this.ad);
        this.af = DoubleCheck.provider(com.vungle.publisher.n.b());
        this.aj = new DelegateFactory();
        this.ag = iy.a(this.o, this.at, this.aj);
        this.ah = iv.a(this.ag);
        this.ai = ix.a(this.o, this.af, this.ah);
        this.aj = DoubleCheck.provider(iw.a(this.ai));
        ((DelegateFactory) this.aj).setDelegatedProvider(this.aj);
        this.ar = new DelegateFactory();
        this.ak = iq.a(this.ar);
        this.al = in.a(this.ak);
        this.ap = new DelegateFactory();
        this.am = hw.a(this.o, this.ap);
        this.an = ht.a(this.am);
        this.ao = hv.a(this.o, this.an);
        this.ap = DoubleCheck.provider(hu.a(this.ao));
        ((DelegateFactory) this.ap).setDelegatedProvider(this.ap);
        this.aq = ip.a(this.al, this.ap);
        this.ar = DoubleCheck.provider(io.a(this.aq));
        ((DelegateFactory) this.ar).setDelegatedProvider(this.ar);
        this.as = it.a(this.o, this.b, this.d, this.ac, this.ae, this.aj, this.ar);
        this.at = DoubleCheck.provider(is.a(this.as));
        ((DelegateFactory) this.at).setDelegatedProvider(this.at);
        this.au = com.vungle.publisher.l.a(this.b, this.at, this.W);
        this.av = com.vungle.publisher.k.a(this.au);
        this.az = new DelegateFactory();
        this.aw = cs.a(this.o, this.az);
        this.ax = cp.a(this.aw);
        this.ay = cr.a(this.o, this.ax);
        this.az = DoubleCheck.provider(cq.a(this.ay));
        ((DelegateFactory) this.az).setDelegatedProvider(this.az);
        this.aA = gi.a(this.C, this.es);
        this.aB = gf.a(this.aA);
        this.aC = gh.a(this.aB);
        this.aD = DoubleCheck.provider(gg.a(this.aC));
        this.aH = new DelegateFactory();
        this.aE = dj.a(this.o, this.aH);
        this.aF = dg.a(this.aE);
        this.aG = di.a(this.o, this.aF);
        this.aH = DoubleCheck.provider(dh.a(this.aG));
        ((DelegateFactory) this.aH).setDelegatedProvider(this.aH);
        this.aI = lc.a(MembersInjectors.noOp());
        this.aJ = le.a(this.aI);
        this.aK = DoubleCheck.provider(ld.a(this.aJ));
        this.bq = new DelegateFactory();
        this.aO = new DelegateFactory();
        this.aL = eq.a(this.o, this.aH, this.aB, this.bq, this.aO, this.aK);
        this.aM = en.a(this.aL);
        this.aN = ep.a(this.o, this.af, this.aD, this.aM);
        this.aO = DoubleCheck.provider(eo.a(this.aN));
        ((DelegateFactory) this.aO).setDelegatedProvider(this.aO);
        this.aP = fy.a(this.o, this.b, this.bq);
        this.aQ = fv.a(this.aP);
        this.aU = new DelegateFactory();
        this.aR = gc.a(this.o, this.bq, this.aU);
        this.aS = fz.a(this.aR);
        this.aT = gb.a(this.o, this.af, this.aS, this.aD);
        this.aU = DoubleCheck.provider(ga.a(this.aT));
        ((DelegateFactory) this.aU).setDelegatedProvider(this.aU);
        this.aV = ef.a(this.o, this.af, this.ac, this.d);
        this.aW = DoubleCheck.provider(ee.a(this.aV));
    }

    private void b(a aVar) {
        this.ba = new DelegateFactory();
        this.aX = ho.a(this.o, this.ba);
        this.aY = hl.a(this.aX);
        this.aZ = hn.a(this.o, this.aY);
        this.ba = hm.a(this.aZ);
        ((DelegateFactory) this.ba).setDelegatedProvider(this.ba);
        this.bb = ev.a(this.o, this.aW, this.d, this.ba, this.ac);
        this.bc = DoubleCheck.provider(es.a(this.bb));
        this.bd = eu.a(this.bc);
        this.be = DoubleCheck.provider(et.a(this.bd));
        this.bf = dz.a(dx.b());
        this.bg = DoubleCheck.provider(dy.a(this.bf));
        this.bo = new DelegateFactory();
        this.bh = fu.a(this.bo);
        this.bi = fr.a(this.bh);
        this.bm = new DelegateFactory();
        this.bj = fa.a(this.o, this.bm);
        this.bk = ex.a(this.bj);
        this.bl = ez.a(this.o, this.bk);
        this.bm = DoubleCheck.provider(ey.a(this.bl));
        ((DelegateFactory) this.bm).setDelegatedProvider(this.bm);
        this.bn = ft.a(this.bi, this.bm);
        this.bo = DoubleCheck.provider(fs.a(this.bn));
        ((DelegateFactory) this.bo).setDelegatedProvider(this.bo);
        this.bp = fx.a(this.o, this.b, this.d, this.ac, this.f, this.aO, this.aQ, this.aU, this.be, this.bg, this.bo);
        this.bq = DoubleCheck.provider(fw.a(this.bp));
        ((DelegateFactory) this.bq).setDelegatedProvider(this.bq);
        this.by = new DelegateFactory();
        this.br = ff.a(this.o, this.by);
        this.bs = fc.a(this.br);
        this.bw = new DelegateFactory();
        this.bt = fl.a(this.o, this.bw);
        this.bu = fi.a(this.bt);
        this.bv = fk.a(this.o, this.bu);
        this.bw = DoubleCheck.provider(fj.a(this.bv));
        ((DelegateFactory) this.bw).setDelegatedProvider(this.bw);
        this.bx = fe.a(this.o, this.bs, this.bw);
        this.by = DoubleCheck.provider(fd.a(this.bx));
        ((DelegateFactory) this.by).setDelegatedProvider(this.by);
        this.bE = new DelegateFactory();
        this.bz = fp.a(this.o, this.d, this.bE, this.by);
        this.bA = fm.a(this.bz);
        this.bB = dv.a(dt.b());
        this.bC = DoubleCheck.provider(du.a(this.bB));
        this.bD = fo.a(this.o, this.az, this.ac, this.bq, this.by, this.bA, this.bC);
        this.bE = DoubleCheck.provider(fn.a(this.bD));
        ((DelegateFactory) this.bE).setDelegatedProvider(this.bE);
        this.bM = new DelegateFactory();
        this.bF = ib.a(this.o, this.bM);
        this.bG = hy.a(this.bF);
        this.bK = new DelegateFactory();
        this.bH = ih.a(this.o, this.bK);
        this.bI = ie.a(this.bH);
        this.bJ = ig.a(this.o, this.bI);
        this.bK = DoubleCheck.provider(Cif.a(this.bJ));
        ((DelegateFactory) this.bK).setDelegatedProvider(this.bK);
        this.bL = ia.a(this.o, this.bG, this.bK);
        this.bM = DoubleCheck.provider(hz.a(this.bL));
        ((DelegateFactory) this.bM).setDelegatedProvider(this.bM);
        this.bQ = new DelegateFactory();
        this.bN = il.a(this.o, this.d, this.bQ, this.bM);
        this.bO = ii.a(this.bN);
        this.bP = ik.a(this.o, this.az, this.ac, this.bM, this.at, this.bO);
        this.bQ = DoubleCheck.provider(ij.a(this.bP));
        ((DelegateFactory) this.bQ).setDelegatedProvider(this.bQ);
        this.cs = new DelegateFactory();
        this.bR = la.a(this.o, this.cs, this.aK);
        this.bS = kx.a(this.bR);
        this.ca = new DelegateFactory();
        this.bT = Cdo.a(this.o, this.cs, this.ca);
        this.bU = dl.a(this.bT);
        this.bY = new DelegateFactory();
        this.bV = jd.a(this.o, this.bY);
        this.bW = ja.a(this.bV);
        this.bX = jc.a(this.o, this.bW);
        this.bY = DoubleCheck.provider(jb.a(this.bX));
        ((DelegateFactory) this.bY).setDelegatedProvider(this.bY);
        this.bZ = dn.a(this.o, this.af, this.bU, this.aD, this.bY);
        this.ca = DoubleCheck.provider(dm.a(this.bZ));
        ((DelegateFactory) this.ca).setDelegatedProvider(this.ca);
        this.cb = jx.a(this.o, this.aW, this.d, this.ba, this.ac);
        this.cc = ju.a(this.cb);
        this.cd = jw.a(this.cc);
        this.ce = DoubleCheck.provider(jv.a(this.cd));
        this.ci = new DelegateFactory();
        this.cf = js.a(this.o, this.aH, this.aB, this.cs, this.ci);
        this.cg = jp.a(this.cf);
        this.ch = jr.a(this.o, this.af, this.aD, this.cg);
        this.ci = DoubleCheck.provider(jq.a(this.ch));
        ((DelegateFactory) this.ci).setDelegatedProvider(this.ci);
        this.cm = new DelegateFactory();
        this.cj = kc.a(this.o, this.cm);
        this.ck = jz.a(this.cj);
        this.cl = kb.a(this.o, this.ck);
        this.cm = DoubleCheck.provider(ka.a(this.cl));
        ((DelegateFactory) this.cm).setDelegatedProvider(this.cm);
        this.cq = new DelegateFactory();
        this.cn = kw.a(this.cq);
        this.co = kt.a(this.cn);
        this.cp = kv.a(this.co, this.cm);
        this.cq = DoubleCheck.provider(ku.a(this.cp));
        ((DelegateFactory) this.cq).setDelegatedProvider(this.cq);
        this.cr = kz.a(this.o, this.b, this.d, this.ac, this.bS, this.ca, this.f, this.ce, this.ci, this.cm, this.cq, this.bY, this.bg);
        this.cs = DoubleCheck.provider(ky.a(this.cr));
        ((DelegateFactory) this.cs).setDelegatedProvider(this.cs);
        this.cA = new DelegateFactory();
        this.ct = kh.a(this.o, this.cA);
        this.cu = ke.a(this.ct);
        this.cy = new DelegateFactory();
        this.cv = kn.a(this.o, this.cy);
        this.cw = kk.a(this.cv);
        this.cx = km.a(this.o, this.cw);
        this.cy = DoubleCheck.provider(kl.a(this.cx));
        ((DelegateFactory) this.cy).setDelegatedProvider(this.cy);
        this.cz = kg.a(this.o, this.cu, this.cy);
        this.cA = DoubleCheck.provider(kf.a(this.cz));
        ((DelegateFactory) this.cA).setDelegatedProvider(this.cA);
        this.cE = new DelegateFactory();
        this.cB = kr.a(this.o, this.d, this.cE);
        this.cC = ko.a(this.cB);
        this.cD = kq.a(this.o, this.az, this.ac, this.cs, this.cA, this.cC, this.bC);
        this.cE = DoubleCheck.provider(kp.a(this.cD));
        ((DelegateFactory) this.cE).setDelegatedProvider(this.cE);
        this.cF = lj.a(MembersInjectors.noOp());
        this.cG = ll.a(this.cF);
        this.cH = DoubleCheck.provider(lk.a(this.cG));
        this.cP = new DelegateFactory();
        this.cI = hj.a(this.o, this.cP, this.cH);
        this.cJ = hg.a(this.cI);
        this.cK = gp.a(this.o, this.aW, this.d, this.ba, this.ac);
        this.cL = DoubleCheck.provider(gm.a(this.cK));
        this.cM = go.a(this.cL);
        this.cN = DoubleCheck.provider(gn.a(this.cM));
        this.cO = hi.a(this.o, this.b, this.d, this.ac, this.cJ, this.cN);
        this.cP = DoubleCheck.provider(hh.a(this.cO));
        ((DelegateFactory) this.cP).setDelegatedProvider(this.cP);
        this.cX = new DelegateFactory();
        this.cQ = gu.a(this.o, this.cX);
        this.cR = gr.a(this.cQ);
        this.cV = new DelegateFactory();
        this.cS = ha.a(this.o, this.cV);
    }

    private void c(a aVar) {
        this.cT = gx.a(this.cS);
        this.cU = gz.a(this.o, this.cT);
        this.cV = DoubleCheck.provider(gy.a(this.cU));
        ((DelegateFactory) this.cV).setDelegatedProvider(this.cV);
        this.cW = gt.a(this.o, this.cR, this.cV);
        this.cX = DoubleCheck.provider(gs.a(this.cW));
        ((DelegateFactory) this.cX).setDelegatedProvider(this.cX);
        this.db = new DelegateFactory();
        this.cY = he.a(this.o, this.d, this.db);
        this.cZ = hb.a(this.cY);
        this.da = hd.a(this.o, this.az, this.ac, this.cP, this.cX, this.cZ);
        this.db = DoubleCheck.provider(hc.a(this.da));
        ((DelegateFactory) this.db).setDelegatedProvider(this.db);
        this.dc = dc.a(this.o, this.bE, this.bQ, this.cE, this.db);
        this.dd = DoubleCheck.provider(db.a(this.dc));
        this.dr = new DelegateFactory();
        this.f13de = ym.a(this.b, this.dd, this.bE, this.dr, this.es, this.bQ);
        this.df = DoubleCheck.provider(yl.a(this.f13de));
        this.dg = zh.a(this.e, this.ep);
        this.dh = DoubleCheck.provider(zg.a(this.dg));
        this.di = DoubleCheck.provider(wq.a(MembersInjectors.noOp()));
        this.dj = DoubleCheck.provider(wb.a(MembersInjectors.noOp()));
        this.dk = wx.a(this.dj);
        this.dl = DoubleCheck.provider(ww.a(this.dk));
        this.dm = wo.a(this.af, this.di, this.dl);
        this.dn = DoubleCheck.provider(wn.a(this.dm));
        this.f3do = s.a(aVar.c);
        this.dp = DoubleCheck.provider(yf.b());
        this.dq = vr.a(this.b, this.m, this.df, this.ep, this.dh, this.dn, this.es, this.f3do, this.W, this.dp, this.ba);
        this.dr = DoubleCheck.provider(vq.a(this.dq));
        ((DelegateFactory) this.dr).setDelegatedProvider(this.dr);
        this.ds = DoubleCheck.provider(AdConfig_Factory.create());
        this.dt = com.vungle.publisher.w.a(this.ds);
        this.du = DoubleCheck.provider(com.vungle.publisher.v.a(this.dt));
        this.dv = de.a(this.bq, this.at, this.cs, this.cP);
        this.dw = DoubleCheck.provider(dd.a(this.dv));
        this.dx = ed.a(this.o, this.af, this.ac, this.dw, this.ce, this.be, this.aW);
        this.dy = DoubleCheck.provider(ec.a(this.dx));
        this.dz = DoubleCheck.provider(ui.b());
        this.dA = ua.a(ty.b());
        this.dB = DoubleCheck.provider(tz.a(this.dA));
        this.dC = tv.a(tt.b());
        this.dD = DoubleCheck.provider(tu.a(this.dC));
        this.dE = ug.a(this.dz, this.dB, this.dD);
        this.dF = DoubleCheck.provider(uf.a(this.dE));
        this.dG = vb.a(this.dF);
        this.dH = va.a(this.dG);
        this.dI = DoubleCheck.provider(ti.a(MembersInjectors.noOp()));
        this.dJ = yc.a(this.dI, uv.b(), this.dH, this.dp);
        this.dK = DoubleCheck.provider(yb.a(this.dJ));
        this.dL = xx.a(this.dd, this.dK, this.dy, this.bq);
        this.dM = xw.a(this.dL);
        this.dN = uy.a(uk.b());
        this.dO = ux.a(this.dN);
        this.dP = wi.a(this.af, this.di, this.dl);
        this.dQ = DoubleCheck.provider(wh.a(this.dP));
        this.dR = wl.a(this.af);
        this.dS = DoubleCheck.provider(wk.a(this.dR));
        this.dT = DoubleCheck.provider(xc.a(MembersInjectors.noOp()));
        this.dU = DoubleCheck.provider(xa.a(MembersInjectors.noOp()));
        this.dV = vv.a(MembersInjectors.noOp());
        this.dW = vx.a(this.dV);
        this.dX = DoubleCheck.provider(vw.a(this.dW));
        this.dY = wt.a(this.af, this.dT, this.dU, this.dX);
        this.dZ = DoubleCheck.provider(ws.a(this.dY));
        this.ea = yi.a(this.dQ, this.dS, this.dZ);
        this.eb = DoubleCheck.provider(yh.a(this.ea));
        this.ec = xf.a(this.dw, this.dy);
        this.ed = DoubleCheck.provider(xe.a(this.ec));
        this.ee = wf.a(this.af);
        this.ef = DoubleCheck.provider(we.a(this.ee));
        this.eg = xp.a(this.dH, this.dM, this.dO, this.eb, this.ed, this.es, this.dp, this.N, this.b, this.ep, this.m, this.ac, this.ef, this.W);
        this.eh = xo.a(this.eg);
        this.ei = com.vungle.publisher.h.a(this.b, this.es, this.e, this.C, this.O, this.P, this.Q, this.m, this.J, this.Y, this.av, this.dr, this.ep, this.du, this.N, this.dy, this.eh, this.W);
        this.ej = DoubleCheck.provider(com.vungle.publisher.g.a(this.ei));
        this.ek = px.a(this.b, this.m, this.ej, this.es);
        this.el = pu.a(this.ek);
        this.em = pw.a(this.el);
        this.en = DoubleCheck.provider(pv.a(this.em));
        this.eo = com.vungle.publisher.env.q.a(this.en, this.v);
        this.ep = DoubleCheck.provider(com.vungle.publisher.env.p.a(this.eo));
        ((DelegateFactory) this.ep).setDelegatedProvider(this.ep);
        this.eq = q.a(aVar.a);
        this.er = com.vungle.publisher.env.v.a(this.d, this.q, this.C, this.b, this.E, this.L, this.m, this.N, this.ep, this.v, this.ac, this.k, this.j, this.eq);
        this.es = DoubleCheck.provider(com.vungle.publisher.env.u.a(this.er));
        ((DelegateFactory) this.es).setDelegatedProvider(this.es);
        this.et = DoubleCheck.provider(zd.b());
        this.eu = pe.a(this.b);
        this.ev = DoubleCheck.provider(pb.a(this.eu));
        this.ew = pd.a(this.ev);
        this.ex = DoubleCheck.provider(pc.a(this.ew));
        this.ey = ud.a(this.dF);
        this.ez = uc.a(this.ey);
        this.eA = DoubleCheck.provider(up.a(MembersInjectors.noOp()));
        this.eB = tg.a(uk.b(), this.m);
        this.eC = tf.a(this.eB);
        this.eD = tp.a(uk.b(), this.m);
        this.eE = to.a(this.eD);
        this.eF = us.a(this.ez, this.eA, this.eC, this.eE);
        this.eG = DoubleCheck.provider(ur.a(this.eF));
        this.eH = tm.a(this.eG, this.m);
        this.eI = tl.a(this.eH);
        this.eJ = yw.a(this.b, this.dd, this.df, this.eI, this.ep, this.dh);
        this.eK = DoubleCheck.provider(yt.a(this.eJ));
        this.eL = yv.a(this.eK);
        this.eM = DoubleCheck.provider(yu.a(this.eL));
        this.eN = DoubleCheck.provider(mu.b());
        this.eO = mx.a(this.e);
    }

    private void d(a aVar) {
        this.eP = DoubleCheck.provider(mw.a(this.eO));
        this.eQ = com.vungle.publisher.image.b.a(this.e);
        this.eR = DoubleCheck.provider(com.vungle.publisher.image.a.a(this.eQ));
        this.eS = zr.a(this.eR);
        this.eT = DoubleCheck.provider(zq.a(this.eS));
        this.eU = oi.a(this.eT, this.b);
        this.eV = DoubleCheck.provider(oh.a(this.eU));
        this.eW = ol.a(this.e, this.eP);
        this.eX = DoubleCheck.provider(ok.a(this.eW));
        this.eY = bf.a(this.t);
        this.eZ = DoubleCheck.provider(be.a(this.eY));
        this.fa = cd.a(this.t, this.eZ, this.b, this.e);
        this.fb = DoubleCheck.provider(cc.a(this.fa));
        this.ff = new DelegateFactory();
        this.fc = ox.a(this.eN, this.eP, this.b, this.ff, this.eV, this.eX, this.C, this.eT, this.fb, this.t, this.dh);
        this.fd = ou.a(this.fc);
        this.fe = ow.a(this.fd);
        this.ff = DoubleCheck.provider(ov.a(this.fe));
        ((DelegateFactory) this.ff).setDelegatedProvider(this.ff);
        this.fg = lh.a(this.aK, this.cH);
        this.fh = DoubleCheck.provider(lg.a(this.fg));
        this.fi = DoubleCheck.provider(md.a(MembersInjectors.noOp()));
        this.fj = mb.a(this.b, this.fi);
        this.fk = DoubleCheck.provider(ma.a(this.fj));
        this.fl = ly.a(this.b);
        this.fm = DoubleCheck.provider(lx.a(this.fl));
        this.fn = oo.a(this.e, this.b, this.fk, this.fm);
        this.fo = DoubleCheck.provider(on.a(this.fn));
        this.fp = of.a(this.eN, this.C, this.b, this.fh, this.e, this.fo);
        this.fq = oc.a(this.fp);
        this.fr = oe.a(this.fq);
        this.fs = DoubleCheck.provider(od.a(this.fr));
        this.ft = pa.a(this.b, this.et, this.C, this.ex, this.eM, this.ff, this.fs, this.ep);
        this.fu = oz.a(this.ft);
        this.fv = yr.a(this.b, this.dd, this.df, this.eI, this.ep, this.az);
        this.fw = yo.a(this.fv);
        this.fx = yq.a(this.fw);
        this.fy = DoubleCheck.provider(yp.a(this.fx));
        this.fz = DoubleCheck.provider(rc.b());
        this.fA = sd.a(this.eP);
        this.fB = sa.a(this.fA);
        this.fC = sc.a(this.fB);
        this.fD = DoubleCheck.provider(sb.a(this.fC));
        this.fE = rt.a(this.eP, this.fz, this.fD);
        this.fF = rs.a(this.fE);
        this.fG = DoubleCheck.provider(rw.b());
        this.fH = rl.a(this.b, this.fF, this.fG, this.c, this.C, this.cs);
        this.fI = ri.a(this.fH);
        this.fJ = rk.a(this.fI, this.bY);
        this.fK = DoubleCheck.provider(rj.a(this.fJ));
        this.fL = re.a(MembersInjectors.noOp());
        this.fM = rn.a(this.e, this.b, this.fK, this.fL, this.fF);
        this.fN = DoubleCheck.provider(rm.a(this.fM));
        this.fO = nh.a(this.b);
        this.fP = DoubleCheck.provider(ne.a(this.fO));
        this.fQ = ng.a(this.fP);
        this.fR = DoubleCheck.provider(nf.a(this.fQ));
        this.fS = rq.a(this.e, this.eP, this.eT);
        this.fT = DoubleCheck.provider(rp.a(this.fS));
        this.fU = nd.a(this.eN, this.C, this.b, this.fh, this.e, this.fN, this.fR, this.fF, this.fT, this.eV);
        this.fV = na.a(this.fU);
        this.fW = nc.a(this.fV);
        this.fX = DoubleCheck.provider(nb.a(this.fW));
        this.fY = nr.a(this.b);
        this.fZ = DoubleCheck.provider(no.a(this.fY));
        this.ga = nq.a(this.fZ);
        this.gb = DoubleCheck.provider(np.a(this.ga));
        this.gc = nn.a(this.b, this.et, this.C, this.fy, this.fX, this.ep, this.gb);
        this.gd = nm.a(this.gc);
        this.ge = nz.a(this.b);
        this.gf = DoubleCheck.provider(nw.a(this.ge));
        this.gg = ny.a(this.gf);
        this.gh = DoubleCheck.provider(nx.a(this.gg));
        this.gi = nv.a(this.b, this.et, this.C, this.fy, this.fX, this.ep, this.eP, this.gh);
        this.gj = nu.a(this.gi);
        this.gk = mi.a(this.fu, this.gd, this.gj);
        this.gl = DoubleCheck.provider(mh.a(this.gk));
        this.gm = VungleAdActivity_MembersInjector.create(this.b, this.c, this.es, this.dw, this.t, this.gl, this.du, this.W);
        this.gn = InitializationEventListener_InitialConfigUpdatedEventListener_MembersInjector.create(this.b, this.ej, this.df, this.es, this.W, this.dr, this.m);
        this.go = DoubleCheck.provider(InitializationEventListener_InitialConfigUpdatedEventListener_Factory.create(this.gn));
        this.gp = InitializationEventListener_MembersInjector.create(this.b, this.m, this.dr, this.go, this.es);
        this.gq = DoubleCheck.provider(InitializationEventListener_Factory.create(this.gp));
        this.gr = qe.a(this.b, this.m);
        this.gs = qb.a(this.gr);
        this.gt = qd.a(this.gs);
        this.gu = DoubleCheck.provider(qc.a(this.gt));
        this.gv = mo.a(this.b, this.C, this.v, this.c);
        this.gw = DoubleCheck.provider(mn.a(this.gv));
        this.gx = VunglePubBase_MembersInjector.create(this.ej, this.gq, this.gu, this.i, this.o, this.C, this.b, this.ds, this.du, this.ep, this.es, this.gw, this.W);
        this.gy = qz.a(this.e, this.k, this.C, this.j, this.eq);
    }

    @Override // com.vungle.publisher.inject.w
    public void a(VungleAdActivity vungleAdActivity) {
        this.gm.injectMembers(vungleAdActivity);
    }

    @Override // com.vungle.publisher.inject.w
    public void a(op opVar) {
        this.fc.injectMembers(opVar);
    }

    @Override // com.vungle.publisher.inject.w
    public void a(my myVar) {
        this.fU.injectMembers(myVar);
    }

    @Override // com.vungle.publisher.inject.w
    public void a(ob obVar) {
        this.fp.injectMembers(obVar);
    }

    @Override // com.vungle.publisher.inject.w
    public void a(VunglePubBase vunglePubBase) {
        this.gx.injectMembers(vunglePubBase);
    }

    @Override // com.vungle.publisher.inject.w
    public void a(AndroidDevice androidDevice) {
        this.A.injectMembers(androidDevice);
    }

    @Override // com.vungle.publisher.inject.w
    public void a(sv svVar) {
        this.H.injectMembers(svVar);
    }

    @Override // com.vungle.publisher.inject.w
    public void a(qw qwVar) {
        this.gy.injectMembers(qwVar);
    }

    /* loaded from: classes4.dex */
    public static final class a {
        private com.vungle.publisher.inject.a a;
        private t b;
        private EndpointModule c;

        private a() {
        }

        public w a() {
            if (this.a == null) {
                this.a = new com.vungle.publisher.inject.a();
            }
            if (this.b == null) {
                this.b = new t();
            }
            if (this.c == null) {
                this.c = new EndpointModule();
            }
            return new r(this);
        }

        public a a(com.vungle.publisher.inject.a aVar) {
            this.a = (com.vungle.publisher.inject.a) Preconditions.checkNotNull(aVar);
            return this;
        }

        public a a(EndpointModule endpointModule) {
            this.c = (EndpointModule) Preconditions.checkNotNull(endpointModule);
            return this;
        }

        public a a(t tVar) {
            this.b = (t) Preconditions.checkNotNull(tVar);
            return this;
        }
    }
}
