package com.applovin.impl.sdk.c;

import java.util.concurrent.TimeUnit;
/* loaded from: classes.dex */
public class a<T> extends b<T> {
    public static final b<String> a = a("afi", "");
    public static final b<Long> b = a("afi_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(5)));
    public static final b<String> c = a("mediation_endpoint", "https://ms.applovin.com/");
    public static final b<String> d = a("mediation_backup_endpoint", "https://ms.applvn.com/");
    public static final b<Long> e = a("fetch_next_ad_retry_delay_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(2)));
    public static final b<Long> f = a("fetch_next_ad_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(5)));
    public static final b<Long> g = a("fetch_mediation_debugger_info_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(7)));
    public static final b<Boolean> h = a("auto_init_mediation_debugger", true);
    public static final b<String> i = a("postback_macros", "{\"{MCODE}\":\"mcode\",\"{BCODE}\":\"bcode\",\"{ICODE}\":\"icode\",\"{SCODE}\":\"scode\"}");
    public static final b<Boolean> j = a("persistent_mediated_postbacks", false);
    public static final b<Long> k = a("max_signal_provider_latency_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(30)));
    public static final b<Long> l = a("default_adapter_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(10)));
    public static final b<Long> m = a("ad_refresh_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(30)));
    public static final b<Long> n = a("ad_load_failure_refresh_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(30)));
    public static final b<String> o = a("ad_load_failure_refresh_ignore_error_codes", "204");
    public static final b<Long> p = a("refresh_ad_on_app_resume_elapsed_threshold_ms", 0L);
    public static final b<Boolean> q = a("refresh_ad_view_timer_responds_to_background", true);
    public static final b<Boolean> r = a("refresh_ad_view_timer_responds_to_store_kit", true);
    public static final b<Boolean> s = a("refresh_ad_view_timer_responds_to_window_visibility_changed", false);
    public static final b<Boolean> t = a("avrsponse", false);
    public static final b<Long> u = a("ad_view_fade_in_animation_ms", 150L);
    public static final b<Long> v = a("ad_view_fade_out_animation_ms", 150L);
    public static final b<Long> w = a("fullscreen_display_delay_ms", 600L);
    public static final b<Long> x = a("ahdm", 500L);
    public static final b<Integer> y = a("ad_load_reminder_delay_seconds", 5);
    public static final b<Long> z = a("ad_view_refresh_precache_request_viewability_undesired_flags", 502L);
    public static final b<Long> A = a("ad_view_refresh_precache_request_delay_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(2)));
    public static final b<Boolean> B = a("ad_view_block_publisher_load_if_refresh_scheduled", true);
    public static final b<Boolean> C = a("fullscreen_ads_block_publisher_load_if_another_showing", true);
    public static final b<Boolean> D = a("fabsina", false);
    public static final b<Long> E = a("ad_expiration_ms", Long.valueOf(TimeUnit.HOURS.toMillis(4)));
    public static final b<Boolean> F = a("saewib", false);
    public static final b<Long> G = a("fullscreen_ad_displayed_timeout_ms", -1L);
    public static final b<Long> H = a("ad_hidden_timeout_ms", -1L);
    public static final b<Boolean> I = a("schedule_ad_hidden_on_ad_dismiss", false);
    public static final b<Long> J = a("ad_hidden_on_ad_dismiss_callback_delay_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(1)));
    public static final b<Boolean> K = a("proe", false);
    public static final b<Integer> L = a("mute_state", 2);
    public static final b<Boolean> M = a("adapters_to_re_fetch_sdk_version_if_empty", true);
    public static final b<String> N = a("saf", "");
    public static final b<String> O = a("saui", "");
    public static final b<Integer> P = a("mra", -1);
    public static final b<String> Q = a("mra_af", "INTER,REWARDED,REWARDED_INTER,BANNER,LEADER,MREC");
    public static final b<Boolean> R = a("pmp", false);
    public static final b<Long> S = a("lpd_s", -1L);
    public static final b<Boolean> T = a("fetch_mediated_ad_gzip", false);
    public static final b<Boolean> U = a("max_postback_gzip", false);
}
