package com.applovin.impl.sdk.c;

import android.net.Uri;
import com.applovin.impl.a.m;
import com.applovin.impl.adview.AppLovinTouchToClickListener;
import com.applovin.mediation.MaxAdFormat;
import com.applovin.sdk.AppLovinAdSize;
import com.google.android.gms.ads.AdRequest;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;
/* loaded from: classes.dex */
public class b<T> implements Comparable {
    public static final b<Long> aA;
    public static final b<Boolean> aB;
    public static final b<Boolean> aC;
    public static final b<Boolean> aD;
    public static final b<Boolean> aE;
    public static final b<Long> aF;
    public static final b<Long> aG;
    public static final b<Long> aH;
    public static final b<Long> aI;
    public static final b<Long> aJ;
    public static final b<Long> aK;
    public static final b<String> aL;
    public static final b<String> aM;
    public static final b<String> aN;
    public static final b<String> aO;
    public static final b<Long> aP;
    public static final b<Integer> aQ;
    public static final b<Integer> aR;
    public static final b<Integer> aS;
    public static final b<Integer> aT;
    public static final b<String> aU;
    public static final b<String> aV;
    public static final b<String> aW;
    public static final b<String> aX;
    public static final b<String> aY;
    public static final b<String> aZ;
    public static final b<Boolean> ac;
    public static final b<String> ad;
    public static final b<Boolean> ae;
    public static final b<String> af;
    public static final b<Long> ag;
    public static final b<Boolean> ah;
    public static final b<String> ai;
    public static final b<String> aj;
    public static final b<String> ak;
    public static final b<String> al;
    public static final b<Boolean> am;
    public static final b<Boolean> an;
    public static final b<Boolean> ao;
    public static final b<Boolean> ap;
    public static final b<Long> aq;
    public static final b<Integer> ar;
    public static final b<Integer> as;
    public static final b<Boolean> at;
    public static final b<Boolean> au;
    public static final b<Boolean> av;
    public static final b<String> aw;
    public static final b<Boolean> ax;
    public static final b<String> ay;
    public static final b<Boolean> az;
    public static final b<String> bA;
    public static final b<String> bB;
    public static final b<String> bC;
    public static final b<String> bD;
    public static final b<Boolean> bE;
    public static final b<String> bF;
    public static final b<String> bG;
    public static final b<String> bH;
    public static final b<String> bI;
    public static final b<Boolean> bJ;
    public static final b<Integer> bK;
    public static final b<Integer> bL;
    public static final b<Boolean> bM;
    public static final b<Long> bN;
    public static final b<Integer> bO;
    public static final b<Integer> bP;
    public static final b<Integer> bQ;
    public static final b<Integer> bR;
    public static final b<Integer> bS;
    public static final b<Integer> bT;
    public static final b<Integer> bU;
    public static final b<Integer> bV;
    public static final b<Float> bW;
    public static final b<Long> bX;
    public static final b<Long> bY;
    public static final b<Integer> bZ;
    public static final b<String> ba;
    public static final b<String> bb;
    public static final b<String> bc;
    public static final b<String> bd;
    public static final b<String> be;
    public static final b<String> bf;
    public static final b<String> bg;
    public static final b<String> bh;
    public static final b<String> bi;
    public static final b<String> bj;
    public static final b<Boolean> bk;
    public static final b<Integer> bl;
    public static final b<Integer> bm;
    public static final b<Long> bn;
    public static final b<Boolean> bo;
    public static final b<Boolean> bp;
    public static final b<Long> bq;
    public static final b<Integer> br;
    public static final b<String> bs;
    public static final b<Boolean> bt;
    public static final b<Boolean> bu;
    public static final b<String> bv;
    public static final b<String> bw;
    public static final b<Integer> bx;
    public static final b<Integer> by;
    public static final b<Boolean> bz;
    public static final b<Integer> cA;
    public static final b<Integer> cB;
    public static final b<Integer> cC;
    public static final b<Long> cD;
    public static final b<Integer> cE;
    public static final b<Integer> cF;
    public static final b<Integer> cG;
    public static final b<Long> cH;
    public static final b<Integer> cI;
    public static final b<Integer> cJ;
    public static final b<Boolean> cK;
    public static final b<Integer> cL;
    public static final b<Integer> cM;
    public static final b<Integer> cN;
    public static final b<Boolean> cO;
    public static final b<Boolean> cP;
    public static final b<Integer> cQ;
    public static final b<Integer> cR;
    public static final b<Integer> cS;
    public static final b<Boolean> cT;
    public static final b<Integer> cU;
    public static final b<Integer> cV;
    public static final b<Boolean> cW;
    public static final b<Boolean> cX;
    public static final b<Integer> cY;
    public static final b<Integer> cZ;
    public static final b<Integer> ca;
    public static final b<Integer> cb;
    public static final b<Boolean> cc;
    public static final b<Integer> cd;
    public static final b<Boolean> ce;
    public static final b<String> cf;
    public static final b<String> cg;

    /* renamed from: ch  reason: collision with root package name */
    public static final b<String> f3929ch;
    public static final b<Integer> ci;
    public static final b<Integer> cj;
    public static final b<Long> ck;
    public static final b<Long> cl;
    public static final b<Boolean> cm;
    public static final b<Integer> cn;
    public static final b<Integer> co;
    public static final b<Integer> cp;
    public static final b<Long> cq;
    public static final b<Long> cr;
    public static final b<Boolean> cs;
    public static final b<Boolean> ct;
    public static final b<Boolean> cu;
    public static final b<Boolean> cv;
    public static final b<Boolean> cw;
    public static final b<Boolean> cx;
    public static final b<Boolean> cy;
    public static final b<Boolean> cz;
    public static final b<String> dA;
    public static final b<Boolean> dB;
    public static final b<Boolean> dC;
    public static final b<Boolean> dD;
    public static final b<Boolean> dE;
    public static final b<Boolean> dF;
    public static final b<Boolean> dG;
    public static final b<Boolean> dH;
    public static final b<Boolean> dI;
    public static final b<Boolean> dJ;
    public static final b<Boolean> dK;
    public static final b<Boolean> dL;
    public static final b<Float> dM;
    public static final b<Boolean> dN;
    public static final b<Boolean> dO;
    public static final b<Boolean> dP;
    public static final b<String> dQ;
    public static final b<Boolean> dR;
    public static final b<Boolean> dS;
    public static final b<Float> dT;
    public static final b<Integer> dU;
    public static final b<Boolean> dV;
    public static final b<Boolean> dW;
    public static final b<Long> dX;
    public static final b<Integer> dY;
    public static final b<Boolean> dZ;
    public static final b<Integer> da;
    public static final b<Integer> db;
    public static final b<Boolean> dc;
    public static final b<Boolean> dd;
    public static final b<Integer> de;
    public static final b<Integer> df;
    public static final b<Boolean> dg;
    public static final b<Boolean> dh;
    public static final b<Boolean> di;
    public static final b<Long> dj;
    public static final b<Integer> dk;
    public static final b<Long> dl;
    public static final b<Integer> dm;
    public static final b<Boolean> dn;

    /* renamed from: do  reason: not valid java name */
    public static final b<Long> f0do;
    public static final b<Long> dp;
    public static final b<Boolean> dq;
    public static final b<Boolean> dr;
    public static final b<Boolean> ds;
    public static final b<Boolean> dt;
    public static final b<Boolean> du;
    public static final b<Boolean> dv;
    public static final b<Boolean> dw;
    public static final b<Boolean> dx;
    public static final b<Boolean> dy;
    public static final b<Boolean> dz;
    public static final b<Boolean> eA;
    public static final b<Boolean> eB;
    public static final b<Boolean> eC;
    public static final b<Boolean> eD;
    public static final b<Boolean> eE;
    public static final b<Boolean> eF;
    public static final b<Boolean> eG;
    public static final b<Boolean> eH;
    public static final b<Boolean> eI;
    public static final b<Boolean> eJ;
    public static final b<Boolean> eK;
    public static final b<Boolean> eL;
    public static final b<Boolean> eM;
    public static final b<Boolean> eN;
    public static final b<Boolean> eO;
    public static final b<Boolean> eP;
    public static final b<Boolean> eQ;
    public static final b<Boolean> eR;
    public static final b<Boolean> eS;
    public static final b<Boolean> eT;
    public static final b<Boolean> eU;
    public static final b<Long> eV;
    public static final b<Long> eW;
    public static final b<Long> eX;
    public static final b<String> eY;
    public static final b<String> eZ;
    public static final b<Long> ea;
    public static final b<Integer> eb;
    public static final b<Boolean> ec;
    public static final b<Boolean> ed;
    public static final b<Integer> ee;
    public static final b<Integer> ef;
    public static final b<Integer> eg;
    public static final b<Boolean> eh;
    public static final b<String> ei;
    public static final b<String> ej;
    public static final b<Integer> ek;
    public static final b<Integer> el;
    public static final b<Long> em;
    public static final b<String> en;
    public static final b<String> eo;
    public static final b<Boolean> ep;
    public static final b<Integer> eq;
    public static final b<Integer> er;
    public static final b<Integer> es;
    public static final b<Boolean> et;
    public static final b<Boolean> eu;
    public static final b<Long> ev;
    public static final b<Long> ew;
    public static final b<Integer> ex;
    public static final b<Boolean> ey;
    public static final b<Boolean> ez;
    public static final b<String> fa;

    /* renamed from: c  reason: collision with root package name */
    private final String f3930c;

    /* renamed from: d  reason: collision with root package name */
    private final T f3931d;
    private static final List<?> a = Arrays.asList(Boolean.class, Float.class, Integer.class, Long.class, String.class);

    /* renamed from: b  reason: collision with root package name */
    private static final Map<String, b<?>> f3928b = new HashMap((int) AdRequest.MAX_CONTENT_URL_LENGTH);

    static {
        Boolean bool = Boolean.FALSE;
        ac = a("is_disabled", bool);
        ad = a("device_id", "");
        Boolean bool2 = Boolean.TRUE;
        ae = a("rss", bool2);
        af = a("device_token", "");
        ag = a("publisher_id", 0L);
        ah = a("is_verbose_logging", bool);
        ai = a("sc", "");
        aj = a("sc2", "");
        ak = a("sc3", "");
        al = a("server_installed_at", "");
        am = a("track_network_response_codes", bool);
        an = a("submit_network_response_codes", bool);
        ao = a("clear_network_response_codes_on_request", bool2);
        ap = a("clear_completion_callback_on_failure", bool);
        aq = a("sicd_ms", 0L);
        ar = a("logcat_max_line_size", 1000);
        as = a("stps", 16);
        at = a("ustp", bool);
        au = a("exception_handler_enabled", bool2);
        av = a("init_omsdk", bool2);
        aw = a("omsdk_partner_name", "applovin");
        ax = a("publisher_can_show_consent_dialog", bool2);
        ay = a("consent_dialog_url", "https://assets.applovin.com/gdpr/flow_v1/gdpr-flow-1.html");
        az = a("consent_dialog_immersive_mode_on", bool);
        aA = a("consent_dialog_show_from_alert_delay_ms", 450L);
        aB = a("alert_consent_for_dialog_rejected", bool);
        aC = a("alert_consent_for_dialog_closed", bool);
        aD = a("alert_consent_for_dialog_closed_with_back_button", bool);
        aE = a("alert_consent_after_init", bool);
        TimeUnit timeUnit = TimeUnit.MINUTES;
        aF = e.a.d.a.a.O(timeUnit, 5L, "alert_consent_after_init_interval_ms");
        aG = e.a.d.a.a.O(timeUnit, 30L, "alert_consent_after_dialog_rejection_interval_ms");
        aH = e.a.d.a.a.O(timeUnit, 5L, "alert_consent_after_dialog_close_interval_ms");
        aI = e.a.d.a.a.O(timeUnit, 5L, "alert_consent_after_dialog_close_with_back_button_interval_ms");
        aJ = e.a.d.a.a.O(timeUnit, 10L, "alert_consent_after_cancel_interval_ms");
        aK = e.a.d.a.a.O(timeUnit, 5L, "alert_consent_reschedule_interval_ms");
        aL = a("text_alert_consent_title", "Make this App Better and Stay Free!");
        aM = a("text_alert_consent_body", "If you don't give us consent to use your data, you will be making our ability to support this app harder, which may negatively affect the user experience.");
        aN = a("text_alert_consent_yes_option", "I Agree");
        aO = a("text_alert_consent_no_option", "Cancel");
        aP = e.a.d.a.a.O(TimeUnit.SECONDS, 1L, "ttc_max_click_duration_ms");
        aQ = a("ttc_max_click_distance_dp", 10);
        AppLovinTouchToClickListener.ClickRecognitionState clickRecognitionState = AppLovinTouchToClickListener.ClickRecognitionState.ACTION_DOWN;
        aR = a("ttc_acrsv2a", Integer.valueOf(clickRecognitionState.ordinal()));
        aS = a("ttc_acrsnmv", Integer.valueOf(clickRecognitionState.ordinal()));
        aT = a("ttc_edge_buffer_dp", 0);
        aU = a("whitelisted_postback_endpoints", "https://prod-a.applovin.com,https://rt.applovin.com/4.0/pix, https://rt.applvn.com/4.0/pix,https://ms.applovin.com/,https://ms.applvn.com/");
        aV = a("fetch_settings_endpoint", "https://ms.applovin.com/");
        aW = a("fetch_settings_backup_endpoint", "https://ms.applvn.com/");
        aX = a("adserver_endpoint", "https://a.applovin.com/");
        aY = a("adserver_backup_endpoint", "https://a.applvn.com/");
        aZ = a("api_endpoint", "https://d.applovin.com/");
        ba = a("api_backup_endpoint", "https://d.applvn.com/");
        bb = a("event_tracking_endpoint_v2", "https://rt.applovin.com/");
        bc = a("event_tracking_backup_endpoint_v2", "https://rt.applvn.com/");
        bd = a("fetch_variables_endpoint", "https://ms.applovin.com/");
        be = a("fetch_variables_backup_endpoint", "https://ms.applvn.com/");
        bf = a("anr_postback_endpoint", "https://ms.applovin.com/1.0/sdk/error");
        bg = a("token_type_prefixes_r", "4!");
        bh = a("token_type_prefixes_arj", "json_v3!");
        bi = a("top_level_events", "landing,paused,resumed,ref,rdf,checkout,iap");
        bj = a("valid_super_property_types", String.class.getName() + "," + Integer.class.getName() + "," + Long.class.getName() + "," + Double.class.getName() + "," + Float.class.getName() + "," + Date.class.getName() + "," + Uri.class.getName() + "," + List.class.getName() + "," + Map.class.getName());
        Boolean bool3 = Boolean.TRUE;
        bk = a("persist_super_properties", bool3);
        bl = a("super_property_string_max_length", 1024);
        bm = a("super_property_url_max_length", 1024);
        bn = e.a.d.a.a.O(timeUnit, 10L, "cached_advertising_info_ttl_ms");
        bo = a("use_per_format_cache_queues", bool3);
        Boolean bool4 = Boolean.FALSE;
        bp = a("cache_cleanup_enabled", bool4);
        bq = a("cache_file_ttl_seconds", Long.valueOf(TimeUnit.DAYS.toSeconds(1L)));
        br = a("cache_max_size_mb", -1);
        bs = a("precache_delimiters", ")]',");
        bt = a("ad_resource_caching_enabled", bool3);
        bu = a("fail_ad_load_on_failed_video_cache", bool3);
        bv = a("resource_cache_prefix", "https://vid.applovin.com/,https://pdn.applovin.com/,https://img.applovin.com/,https://d.applovin.com/,https://assets.applovin.com/,https://cdnjs.cloudflare.com/,http://vid.applovin.com/,http://pdn.applovin.com/,http://img.applovin.com/,http://d.applovin.com/,http://assets.applovin.com/,http://cdnjs.cloudflare.com/");
        bw = a("preserved_cached_assets", "sound_off.png,sound_on.png,closeOptOut.png,1381250003_28x28.png,zepto-1.1.3.min.js,jquery-2.1.1.min.js,jquery-1.9.1.min.js,jquery.knob.js");
        bx = a("vr_retry_count_v1", 1);
        by = a("cr_retry_count_v1", 1);
        bz = a("incent_warning_enabled", bool4);
        bA = a("text_incent_warning_title", "Attention!");
        bB = a("text_incent_warning_body", "You won’t get your reward if the video hasn’t finished.");
        bC = a("text_incent_warning_close_option", "Close");
        bD = a("text_incent_warning_continue_option", "Keep Watching");
        bE = a("incent_nonvideo_warning_enabled", bool4);
        bF = a("text_incent_nonvideo_warning_title", "Attention!");
        bG = a("text_incent_nonvideo_warning_body", "You won’t get your reward if the game hasn’t finished.");
        bH = a("text_incent_nonvideo_warning_close_option", "Close");
        bI = a("text_incent_nonvideo_warning_continue_option", "Keep Playing");
        bJ = a("check_webview_has_gesture", bool4);
        bK = a("close_button_touch_area", 0);
        bL = a("close_button_outside_touch_area", 0);
        bM = a("creative_debugger_enabled", bool4);
        TimeUnit timeUnit2 = TimeUnit.SECONDS;
        bN = e.a.d.a.a.O(timeUnit2, 1L, "viewability_adview_imp_delay_ms");
        bO = a("viewability_adview_banner_min_width", 320);
        bP = a("viewability_adview_banner_min_height", Integer.valueOf(AppLovinAdSize.BANNER.getHeight()));
        MaxAdFormat maxAdFormat = MaxAdFormat.MREC;
        bQ = a("viewability_adview_mrec_min_width", Integer.valueOf(maxAdFormat.getSize().getWidth()));
        bR = a("viewability_adview_mrec_min_height", Integer.valueOf(maxAdFormat.getSize().getHeight()));
        bS = a("viewability_adview_leader_min_width", 728);
        bT = a("viewability_adview_leader_min_height", Integer.valueOf(AppLovinAdSize.LEADER.getHeight()));
        bU = a("viewability_adview_native_min_width", 0);
        bV = a("viewability_adview_native_min_height", 0);
        bW = a("viewability_adview_min_alpha", Float.valueOf(10.0f));
        bX = e.a.d.a.a.O(timeUnit2, 1L, "viewability_timer_min_visible_ms");
        bY = a("viewability_timer_interval_ms", 100L);
        bZ = a("expandable_close_button_size", 27);
        ca = a("expandable_h_close_button_margin", 10);
        cb = a("expandable_t_close_button_margin", 10);
        cc = a("expandable_lhs_close_button", bool4);
        cd = a("expandable_close_button_touch_area", 0);
        ce = a("iaad", bool4);
        cf = a("js_tag_schemes", "applovin,mopub");
        cg = a("js_tag_load_success_hosts", "load,load_succeeded");
        f3929ch = a("js_tag_load_failure_hosts", "failLoad,load_failed");
        ci = a("auxiliary_operations_threads", 3);
        cj = a("caching_operations_threads", 8);
        ck = e.a.d.a.a.O(timeUnit2, 10L, "fullscreen_ad_pending_display_state_timeout_ms");
        cl = e.a.d.a.a.O(TimeUnit.MINUTES, 2L, "fullscreen_ad_showing_state_timeout_ms");
        Boolean bool5 = Boolean.FALSE;
        cm = a("lhs_close_button_video", bool5);
        cn = a("close_button_right_margin_video", 4);
        co = a("close_button_size_video", 30);
        cp = a("close_button_top_margin_video", 8);
        cq = a("inter_display_delay", 200L);
        cr = a("maximum_close_button_delay_seconds", 999L);
        Boolean bool6 = Boolean.TRUE;
        cs = a("respect_close_button", bool6);
        ct = a("lhs_skip_button", bool6);
        cu = a("track_app_killed", bool5);
        cv = a("mute_controls_enabled", bool5);
        cw = a("allow_user_muting", bool6);
        cx = a("mute_videos", bool5);
        cy = a("show_mute_by_default", bool5);
        cz = a("mute_with_user_settings", bool6);
        cA = a("mute_button_size", 32);
        cB = a("mute_button_margin", 10);
        cC = a("mute_button_gravity", 85);
        cD = a("progress_bar_step", 25L);
        cE = a("progress_bar_scale", 10000);
        cF = a("progress_bar_vertical_padding", -8);
        cG = a("vs_buffer_indicator_size", 50);
        cH = a("set_poststitial_muted_initial_delay_ms", 500L);
        cI = a("minepsv", -1);
        cJ = a("maxepsv", -1);
        cK = a("pctfnc", bool5);
        TimeUnit timeUnit3 = TimeUnit.SECONDS;
        cL = a("submit_postback_timeout", Integer.valueOf((int) timeUnit3.toMillis(10L)));
        cM = a("submit_postback_retries", 4);
        cN = a("max_postback_attempts", 3);
        cO = a("fppopq", bool5);
        cP = a("retry_on_all_errors", bool5);
        cQ = a("get_retry_delay_v1", Integer.valueOf((int) timeUnit3.toMillis(10L)));
        cR = a("http_connection_timeout", Integer.valueOf((int) timeUnit3.toMillis(30L)));
        cS = a("http_socket_timeout", Integer.valueOf((int) timeUnit3.toMillis(20L)));
        cT = a("force_ssl", bool5);
        cU = a("fetch_ad_connection_timeout", Integer.valueOf((int) timeUnit3.toMillis(30L)));
        cV = a("fetch_ad_retry_count_v1", 1);
        cW = a("faer", bool5);
        cX = a("faroae", bool5);
        cY = a("submit_data_retry_count_v1", 1);
        cZ = a("response_buffer_size", 16000);
        da = a("fetch_basic_settings_connection_timeout_ms", Integer.valueOf((int) timeUnit3.toMillis(10L)));
        db = a("fetch_basic_settings_retry_count", 3);
        dc = a("fetch_basic_settings_on_reconnect", bool5);
        dd = a("skip_fetch_basic_settings_if_not_connected", bool5);
        de = a("fetch_basic_settings_retry_delay_ms", Integer.valueOf((int) timeUnit3.toMillis(2L)));
        df = a("fetch_variables_connection_timeout_ms", Integer.valueOf((int) timeUnit3.toMillis(5L)));
        dg = a("idflrwbe", bool5);
        dh = a("falawpr", bool5);
        Boolean bool7 = Boolean.FALSE;
        di = a("sort_query_parameters", bool7);
        dj = e.a.d.a.a.O(timeUnit3, 10L, "communicator_request_timeout_ms");
        dk = a("communicator_request_retry_count", 3);
        dl = e.a.d.a.a.O(timeUnit3, 2L, "communicator_request_retry_delay_ms");
        dm = a("ad_session_minutes", 60);
        dn = a("session_tracking_cooldown_on_event_fire", bool6);
        f0do = a("session_tracking_resumed_cooldown_minutes", 90L);
        dp = a("session_tracking_paused_cooldown_minutes", 90L);
        dq = a("qq", bool7);
        Boolean bool8 = Boolean.TRUE;
        dr = a("qq1", bool8);
        ds = a("qq2", bool8);
        dt = a("qq3", bool8);
        du = a("qq4", bool8);
        dv = a("qq5", bool8);
        dw = a("qq6", bool8);
        dx = a("qq7", bool8);
        dy = a("qq8", bool8);
        dz = a("pui", bool8);
        dA = a("plugin_version", "");
        dB = a("hgn", bool7);
        dC = a("cso", bool7);
        dD = a("cfs", bool7);
        dE = a("cmi", bool7);
        dF = a("crat", bool7);
        dG = a("cvs", bool7);
        dH = a("caf", bool7);
        dI = a("cf", bool7);
        dJ = a("cmtl", bool8);
        dK = a("cnr", bool7);
        dL = a("adr", bool7);
        dM = a("volume_normalization_factor", Float.valueOf(6.6666665f));
        dN = a("system_user_agent_collection_enabled", bool7);
        dO = a("user_agent_collection_enabled", bool7);
        dP = a("http_headers_collection_enabled", bool7);
        dQ = a("webview_package_name", "com.google.android.webview");
        dR = a("collect_device_angle", bool7);
        dS = a("collect_device_movement", bool7);
        dT = a("movement_degradation", Float.valueOf(0.75f));
        dU = a("device_sensor_period_ms", 250);
        dV = a("dte", bool8);
        dW = a("idcw", bool7);
        dX = a("anr_debug_thread_refresh_time_ms", -1L);
        dY = a("fetch_basic_settings_delay_ms", 0);
        dZ = a("cclia", bool8);
        ea = a("lccdm", 10L);
        eb = a("lmfd", 3);
        ec = a("is_track_ad_info", bool8);
        ed = a("submit_ad_stats_enabled", bool7);
        TimeUnit timeUnit4 = TimeUnit.SECONDS;
        ee = a("submit_ad_stats_connection_timeout", Integer.valueOf((int) timeUnit4.toMillis(30L)));
        ef = a("submit_ad_stats_retry_count", 1);
        eg = a("submit_ad_stats_max_count", 500);
        Boolean bool9 = Boolean.FALSE;
        eh = a("asdm", bool9);
        ei = a("vast_image_html", "<html><head><style>html,body{height:100%;width:100%}body{background-image:url({SOURCE});background-repeat:no-repeat;background-size:contain;background-position:center;}a{position:absolute;top:0;bottom:0;left:0;right:0}</style></head><body><a href=\"applovin://com.applovin.sdk/adservice/track_click_now\"></a></body></html>");
        ej = a("vast_link_html", "<html><head><style>html,body,iframe{height:100%;width:100%;}body{margin:0}iframe{border:0;overflow:hidden;position:absolute}</style></head><body><iframe src={SOURCE} frameborder=0></iframe></body></html>");
        ek = a("vast_max_response_length", 640000);
        el = a("vast_max_wrapper_depth", 5);
        em = e.a.d.a.a.O(timeUnit4, 1L, "vast_progress_tracking_countdown_step");
        en = a("vast_unsupported_video_extensions", "ogv,flv");
        eo = a("vast_unsupported_video_types", "video/ogg,video/x-flv");
        Boolean bool10 = Boolean.TRUE;
        ep = a("vast_validate_with_extension_if_no_video_type", bool10);
        eq = a("vast_video_selection_policy", Integer.valueOf(m.a.MEDIUM.ordinal()));
        er = a("vast_wrapper_resolution_retry_count_v1", 1);
        es = a("vast_wrapper_resolution_connection_timeout", Integer.valueOf((int) timeUnit4.toMillis(30L)));
        et = a("ree", bool10);
        eu = a("btee", bool10);
        ev = a("server_timestamp_ms", 0L);
        ew = a("device_timestamp_ms", 0L);
        ex = a("gzip_min_length", 0);
        ey = a("gzip_encoding_default", bool9);
        ez = a("fetch_settings_gzip", bool9);
        eA = a("device_init_gzip", bool9);
        eB = a("fetch_ad_gzip", bool9);
        eC = a("event_tracking_gzip", bool9);
        eD = a("submit_ad_stats_gzip", bool9);
        eE = a("reward_postback_gzip", bool9);
        eF = a("force_rerender", bool9);
        eG = a("daostr", bool9);
        eH = a("tctlaa", bool9);
        eI = a("rwvdv", bool9);
        eJ = a("handle_render_process_gone", bool10);
        eK = a("comcr", bool10);
        eL = a("gcoas", bool9);
        eM = a("teorpc", bool9);
        eN = a("rmpibt", bool9);
        eO = a("spbcioa", bool9);
        eP = a("set_webview_render_process_client", bool9);
        eQ = a("disable_webview_hardware_acceleration", bool9);
        eR = a("fvrunc", bool9);
        eS = a("dsaovcf", bool9);
        eT = a("daoar", bool9);
        eU = a("anr_detection_enabled", bool9);
        eV = a("anr_trigger_millis", 4000L);
        eW = a("anr_touch_millis", 3000L);
        eX = a("anr_check_millis", 3000L);
        eY = a("config_consent_dialog_state", "unknown");
        eZ = a("country_code", "");
        fa = a("c_sticky_topics", "user_engagement_sdk_init,adjust_init,safedk_init,discovery_init,max_ad_events,send_http_request,adapter_initialization_status,privacy_setting_updated,network_sdk_version_updated");
    }

    public b(String str, T t) {
        if (str == null) {
            throw new IllegalArgumentException("No name specified");
        }
        if (t == null) {
            throw new IllegalArgumentException("No default value specified");
        }
        this.f3930c = str;
        this.f3931d = t;
    }

    public static <T> b<T> a(String str, T t) {
        if (t != null) {
            if (!a.contains(t.getClass())) {
                StringBuilder y = e.a.d.a.a.y("Unsupported value type: ");
                y.append(t.getClass());
                throw new IllegalArgumentException(y.toString());
            }
            b<T> bVar = new b<>(str, t);
            Map<String, b<?>> map = f3928b;
            if (map.containsKey(str)) {
                throw new IllegalArgumentException(e.a.d.a.a.k("Setting has already been used: ", str));
            }
            map.put(str, bVar);
            return bVar;
        }
        throw new IllegalArgumentException("No default value specified");
    }

    public static Collection<b<?>> c() {
        return Collections.synchronizedCollection(f3928b.values());
    }

    public T a(Object obj) {
        return (T) this.f3931d.getClass().cast(obj);
    }

    public String a() {
        return this.f3930c;
    }

    public T b() {
        return this.f3931d;
    }

    @Override // java.lang.Comparable
    public int compareTo(Object obj) {
        if (obj instanceof b) {
            return this.f3930c.compareTo(((b) obj).a());
        }
        return 0;
    }
}
